"use strict";
const test=require("node:test"); const assert=require("node:assert/strict");
const {createInMemoryDataScopeRepository,createDataScopeAssignmentService,createDataScopeEvaluator,resourceMatchesConstraint,createLmsDataScopeAdapter,DATA_SCOPE_REASON_CODES,CACHE_KEYS}=Object.assign({},require("../authorization/data-scope"),require("../authorization/data-scope/adapters/lmsDataScopeAdapter"));
function taxonomy(status="active"){return{async resolvePublishedDimensionValue({organizationId,valueId,dimensionKey}){return {status,value:{id:valueId,logtoOrganizationId:organizationId,dimensionKeyCache:dimensionKey}}}}}

test("assignment schema semantics require exactly one target and distinct dimension vs relationship keys",async()=>{const repo=createInMemoryDataScopeRepository(); const svc=createDataScopeAssignmentService({repository:repo,taxonomyPort:taxonomy()}); await assert.rejects(()=>svc.previewAssignment({organizationId:"org",userId:"u",logtoRoleId:"r",capability:"lms",scopeKind:"dimension",dimensionKey:"academic.subject"}),/data_scope_exactly_one_target_required/); await assert.rejects(()=>svc.previewAssignment({organizationId:"org",userId:"u",logtoRoleId:"r",capability:"lms",scopeKind:"dimension",dimensionKey:"academic.assigned_group",dimensionValueId:"x"}),/data_scope_dimension_unknown/); await assert.rejects(()=>svc.previewAssignment({organizationId:"org",userId:"u",logtoRoleId:"r",capability:"lms",scopeKind:"resource",dimensionKey:"academic.subject",relationshipKey:"academic.assigned_course",resourceRef:"course-1"}),/data_scope_resource_unknown/); const preview=await svc.previewAssignment({organizationId:"org",userId:"u",logtoRoleId:"r",capability:"lms",scopeKind:"dimension",dimensionKey:"academic.subject",dimensionValueId:"math"}); assert.equal(preview.valid,true); assert.equal(preview.mutated,false);});

test("taxonomy status is enforced and identity.self is not stored as an assignment",async()=>{const repo=createInMemoryDataScopeRepository(); const archived=createDataScopeAssignmentService({repository:repo,taxonomyPort:taxonomy("archived")}); await assert.rejects(()=>archived.createAssignment({organizationId:"org",userId:"u",logtoRoleId:"r",capability:"lms",scopeKind:"dimension",dimensionKey:"academic.subject",dimensionValueId:"math",actorLogtoUserId:"admin"}),/data_scope_dimension_value_archived/); const ok=createDataScopeAssignmentService({repository:repo,taxonomyPort:taxonomy()}); await assert.rejects(()=>ok.createAssignment({organizationId:"org",userId:"u",logtoRoleId:"r",capability:"lms",scopeKind:"dimension",dimensionKey:"identity.self",dimensionValueId:"self",actorLogtoUserId:"admin"}),/data_scope_dimension_unknown/);});

test("partial uniqueness blocks active duplicates but revoked history allows reassignment",async()=>{const repo=createInMemoryDataScopeRepository(); const svc=createDataScopeAssignmentService({repository:repo,taxonomyPort:taxonomy()}); const input={organizationId:"org",userId:"u",logtoRoleId:"role_headteacher",capability:"lms",scopeKind:"dimension",dimensionKey:"academic.subject",dimensionValueId:"math",actorLogtoUserId:"admin"}; const first=await svc.createAssignment(input); await assert.rejects(()=>svc.createAssignment(input),/data_scope_assignment_duplicate/); await svc.revokeAssignment({organizationId:"org",assignmentId:first.assignment.id,actorLogtoUserId:"admin"}); const second=await svc.createAssignment(input); assert.notEqual(second.assignment.id,first.assignment.id);});

test("dimension strategy composes OR within a dimension and AND between required dimensions",async()=>{const repo=createInMemoryDataScopeRepository(); const svc=createDataScopeAssignmentService({repository:repo,taxonomyPort:taxonomy()}); await svc.createAssignment({organizationId:"org",userId:"ana",logtoRoleId:"role_head",capability:"lms",scopeKind:"dimension",dimensionKey:"academic.section",dimensionValueId:"primary",actorLogtoUserId:"admin"}); await svc.createAssignment({organizationId:"org",userId:"ana",logtoRoleId:"role_head",capability:"lms",scopeKind:"dimension",dimensionKey:"academic.section",dimensionValueId:"preschool",actorLogtoUserId:"admin"}); const evaluator=createDataScopeEvaluator({repository:repo,roleIdToKey:{role_head:"organization_headdirector"}}); const d=await evaluator.evaluate({organizationId:"org",principal:{subject:"ana",scopes:["lms.grades.read"],rolePaths:[{logtoRoleId:"role_head"}]},permission:"lms.grades.read",capability:"lms"}); assert.equal(d.allowed,true); assert.deepEqual(d.constraint.clauses[0].valueIds.sort(),["preschool","primary"]);});

test("multiple role paths do not mix permission from one path with scope from another",async()=>{const repo=createInMemoryDataScopeRepository(); const svc=createDataScopeAssignmentService({repository:repo,taxonomyPort:taxonomy()}); await svc.createAssignment({organizationId:"org",userId:"ana",logtoRoleId:"role_scope_only",capability:"lms",scopeKind:"dimension",dimensionKey:"academic.subject",dimensionValueId:"math",actorLogtoUserId:"admin"}); const evaluator=createDataScopeEvaluator({repository:repo,roleIdToKey:{role_permission_only:"organization_headteacher",role_scope_only:"organization_headteacher"}}); const d=await evaluator.evaluate({organizationId:"org",principal:{subject:"ana",scopes:["lms.grades.read"],rolePaths:[{logtoRoleId:"role_permission_only"},{logtoRoleId:"role_scope_only",tokenScopePresent:false}]},permission:"lms.grades.read",capability:"lms"}); assert.equal(d.allowed,false); assert.equal(d.reasonCode,DATA_SCOPE_REASON_CODES.MULTIPLE_ROLE_PATHS_INCOMPLETE);});

test("relationships consume #98 ScopeCandidate provenance and groups never grant permission",async()=>{const repo=createInMemoryDataScopeRepository(); const provider={async listCandidates(){return[{candidateId:"cand-1",organizationId:"org",subjectId:"t",logtoRoleId:"role_teacher",capability:"lms",dimensionKey:"academic.subject",unitId:"unit-math",source:{type:"unit_membership",id:"mem-1",relationshipType:"teaches",translationRuleId:"academic-department-teaches-to-subject",translationRuleVersion:"1"},validFrom:"2026-01-01T00:00:00Z",structureVersion:"4"}]}}; const evaluator=createDataScopeEvaluator({repository:repo,scopeCandidateProvider:provider,roleIdToKey:{role_teacher:"organization_teacher"}}); const d=await evaluator.evaluate({organizationId:"org",principal:{subject:"t",scopes:["lms.grades.read"],rolePaths:[{logtoRoleId:"role_teacher"}]},permission:"lms.grades.read",capability:"lms",now:new Date("2026-02-01T00:00:00Z")}); assert.equal(d.allowed,true); assert.equal(d.rolePaths[0].scopeCandidateIds[0],"cand-1"); assert.equal(d.rolePaths[0].constraint.kind,"relationships"); assert.equal(d.rolePaths[0].permission,"lms.grades.read");});

test("self strategy needs no assignment row and resource matching is backend-owned",async()=>{const repo=createInMemoryDataScopeRepository(); const evaluator=createDataScopeEvaluator({repository:repo,roleIdToKey:{role_student:"organization_student"}}); const d=await evaluator.evaluate({organizationId:"org",principal:{subject:"student-1",scopes:["lms.grades.read"],rolePaths:[{logtoRoleId:"role_student"}]},permission:"lms.grades.read",capability:"lms"}); assert.equal(d.constraint.kind,"self"); assert.equal(resourceMatchesConstraint({organizationId:"org",subjectId:"student-1"},d.constraint),true); assert.equal(resourceMatchesConstraint({organizationId:"org",subjectId:"student-2"},d.constraint),false); assert.equal((await repo.listAssignments({organizationId:"org"})).length,0);});

test("LMS adapter applies the same constraint to list/detail/mutation/count/export/bulk",async()=>{const provider={async getResource({resourceId}){return resourceId==="g1"?{organizationId:"org",dimensions:{"academic.subject":"math"},relationships:{}}:{organizationId:"org",dimensions:{"academic.subject":"science"},relationships:{}}}}; const adapter=createLmsDataScopeAdapter({resourceProvider:provider}); const constraint={kind:"dimensions",clauses:[{dimensionKey:"academic.subject",operator:"in",valueIds:["math"]}]}; assert.deepEqual(adapter.compileListConstraint({organizationId:"org"},constraint,{}).dataScopeConstraint,constraint); assert.equal((await adapter.assertResourceScope({organizationId:"org"},constraint,"g1")).allowed,true); assert.equal((await adapter.assertResourceScope({organizationId:"org"},constraint,"g2")).allowed,false); assert.equal((await adapter.assertMutationScope({organizationId:"org"},constraint,{resourceId:"g1",nextResource:{organizationId:"org",dimensions:{"academic.subject":"science"}}})).allowed,false); assert.equal(adapter.applyBulkScope({organizationId:"org"},constraint,["g1"]).mode,"all-or-nothing");});

test("runtime cache keys are versioned and do not contain assignments",()=>{const key=CACHE_KEYS.dataScope({orgId:"org",userId:"u",policyVersion:31}); assert.equal(key,"civitas:authz:data-scope:v1:org:u:31"); assert.equal(key.includes("math"),false);});

test("scope assignments are bound to membership role paths and cannot be borrowed by same role",async()=>{const repo=createInMemoryDataScopeRepository(); const svc=createDataScopeAssignmentService({repository:repo,taxonomyPort:taxonomy()}); await svc.createAssignment({organizationId:"org",userId:"ana",membershipId:"membership_math",logtoRoleId:"role_headteacher",canonicalRoleId:"role_headteacher",capability:"lms",scopeKind:"dimension",dimensionKey:"academic.subject",dimensionValueId:"math",actorLogtoUserId:"admin"}); const evaluator=createDataScopeEvaluator({repository:repo,roleIdToKey:{role_headteacher:"organization_headteacher"}}); const denied=await evaluator.evaluate({organizationId:"org",principal:{subject:"ana",scopes:["lms.grades.read"],rolePaths:[{membershipId:"membership_science",logtoRoleId:"role_headteacher",canonicalRoleId:"role_headteacher"}]},permission:"lms.grades.read",capability:"lms"}); assert.equal(denied.allowed,false); const allowed=await evaluator.evaluate({organizationId:"org",principal:{subject:"ana",scopes:["lms.grades.read"],rolePaths:[{membershipId:"membership_math",logtoRoleId:"role_headteacher",canonicalRoleId:"role_headteacher"}]},permission:"lms.grades.read",capability:"lms"}); assert.equal(allowed.allowed,true); assert.equal(allowed.rolePaths[0].assignmentIds.length,1);});

test("scope templates are owner-published semantics and tenant labels cannot change strategy",async()=>{const {createOwnerScopeTemplateRegistry,OWNER_SCOPE_TEMPLATE_VERSION}=require("../authorization/data-scope"); const repo=createInMemoryDataScopeRepository(); const templateRegistry=createOwnerScopeTemplateRegistry(); const svc=createDataScopeAssignmentService({repository:repo,taxonomyPort:taxonomy(),templateRegistry}); await svc.createAssignment({organizationId:"org",userId:"ana",membershipId:"membership_math",logtoRoleId:"role_headteacher",canonicalRoleId:"role_headteacher",roleKey:"organization_headteacher",scopeTemplateId:"lms.organization_headteacher.dimensions",scopeTemplateVersion:OWNER_SCOPE_TEMPLATE_VERSION,capability:"lms",scopeKind:"dimension",dimensionKey:"academic.subject",dimensionValueId:"math",actorLogtoUserId:"admin"}); await assert.rejects(()=>svc.createAssignment({organizationId:"org",userId:"ana",membershipId:"membership_bad",logtoRoleId:"role_headteacher",canonicalRoleId:"role_headteacher",roleKey:"organization_headteacher",scopeTemplateId:"lms.organization_headteacher.dimensions",scopeTemplateVersion:OWNER_SCOPE_TEMPLATE_VERSION,capability:"lms",scopeKind:"resource",relationshipKey:"academic.assigned_course",resourceRef:"course-1",actorLogtoUserId:"admin"}),/data_scope_template_target_forbidden/);});
