"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { createInMemoryOrganizationStructureRepository, createUnitService, createUnitMembershipService, createScopeCandidateResolver, createScopeProjectionReconciler, createSourceValidationProvider, createAccessImpactService, createBackfillPlanService, buildReconciliationJobPayload, assertSafeJobPayload } = require("../organization-structure");
const { createInMemoryDataScopeRepository, createDataScopeAssignmentService, createDataScopeEvaluator } = require("../authorization/data-scope");
function taxonomy(status = "active") { return { async resolvePublishedDimensionValue({ organizationId, valueId, dimensionKey }) { return { status, value: { id: valueId, logtoOrganizationId: organizationId, dimensionKeyCache: dimensionKey } }; } }; }
async function fixture() { const orgRepo = createInMemoryOrganizationStructureRepository(); const dataRepo = createInMemoryDataScopeRepository(); const unitSvc = createUnitService({ repository: orgRepo, taxonomyPort: taxonomy() }); const memSvc = createUnitMembershipService({ repository: orgRepo }); const unit = await unitSvc.createUnit({ organizationId: "org", hierarchyKey: "academic_structure", unitType: "academic_department", stableKey: "math", displayName: "Math", dimensionValueId: "math-tax", actorLogtoUserId: "admin" }); await unitSvc.activateUnit({ organizationId: "org", unitId: unit.id, actorLogtoUserId: "admin" }); const membership = await memSvc.assignMembership({ organizationId: "org", unitId: unit.id, logtoUserId: "ana", logtoRoleId: "role_teacher", relationshipType: "teaches", actorLogtoUserId: "admin", validFrom: "2026-01-01T00:00:00Z" }); const candidateResolver = createScopeCandidateResolver({ repository: orgRepo, taxonomyPort: taxonomy() }); const candidateProvider = { async listCandidates({ organizationId, subjectId, sourceIds }) { const memberships = await orgRepo.listMemberships({ organizationId, logtoUserId: subjectId }); const selected = sourceIds?.length ? memberships.filter((m) => sourceIds.includes(m.id)) : memberships; const out = []; for (const m of selected) out.push(...await candidateResolver.resolveCandidatesForMembership({ organizationId, membershipId: m.id, now: new Date("2026-02-01T00:00:00Z") })); return out; } }; const dataSvc = createDataScopeAssignmentService({ repository: dataRepo, taxonomyPort: taxonomy() }); return { orgRepo, dataRepo, unit, membership, candidateProvider, dataSvc, memSvc }; }

test("derived grant is eventual: candidate exists, projection pending denies, reconciliation materializes", async () => { const f = await fixture(); const evaluatorBefore = createDataScopeEvaluator({ repository: f.dataRepo, scopeCandidateProvider: { async listCandidates() { return []; } }, roleIdToKey: { role_teacher: "organization_teacher" } }); const before = await evaluatorBefore.evaluate({ organizationId: "org", principal: { subject: "ana", scopes: ["lms.grades.read"], rolePaths: [{ logtoRoleId: "role_teacher" }] }, permission: "lms.grades.read", capability: "lms", now: new Date("2026-02-01T00:00:00Z") }); assert.equal(before.allowed, false); const reconciler = createScopeProjectionReconciler({ dataScopeRepository: f.dataRepo, dataScopeAssignmentService: f.dataSvc, candidateProvider: f.candidateProvider, sourceProvider: createSourceValidationProvider({ organizationStructureRepository: f.orgRepo }), taxonomyPort: taxonomy() }); const result = await reconciler.reconcileScopeCandidates({ organizationId: "org", subjectId: "ana" }); assert.equal(result.created.length, 1); const after = await createDataScopeEvaluator({ repository: f.dataRepo, roleIdToKey: { role_teacher: "organization_headteacher" } }).evaluate({ organizationId: "org", principal: { subject: "ana", scopes: ["lms.grades.read"], rolePaths: [{ logtoRoleId: "role_teacher" }] }, permission: "lms.grades.read", capability: "lms" }); assert.equal(after.allowed, true); });

test("revoked membership removes scope immediately even before projection cleanup", async () => { const f = await fixture(); const sourceValidator = createSourceValidationProvider({ organizationStructureRepository: f.orgRepo }); const reconciler = createScopeProjectionReconciler({ dataScopeRepository: f.dataRepo, dataScopeAssignmentService: f.dataSvc, candidateProvider: f.candidateProvider, sourceProvider: sourceValidator, taxonomyPort: taxonomy() }); await reconciler.reconcileScopeCandidates({ organizationId: "org", subjectId: "ana" }); await f.memSvc.revokeMembership({ organizationId: "org", membershipId: f.membership.id, actorLogtoUserId: "admin" }); const decision = await createDataScopeEvaluator({ repository: f.dataRepo, sourceValidator, roleIdToKey: { role_teacher: "organization_teacher" } }).evaluate({ organizationId: "org", principal: { subject: "ana", scopes: ["lms.grades.read"], rolePaths: [{ logtoRoleId: "role_teacher" }] }, permission: "lms.grades.read", capability: "lms" }); assert.equal(decision.allowed, false); const cleanup = await reconciler.revokeSourceDerivedScopes({ organizationId: "org", sourceType: "unit_membership", sourceIds: [f.membership.id] }); assert.equal(cleanup.revoked.length, 1); });

test("reconciliation is idempotent and duplicate jobs do not double grant", async () => { const f = await fixture(); const reconciler = createScopeProjectionReconciler({ dataScopeRepository: f.dataRepo, dataScopeAssignmentService: f.dataSvc, candidateProvider: f.candidateProvider, sourceProvider: createSourceValidationProvider({ organizationStructureRepository: f.orgRepo }), taxonomyPort: taxonomy() }); await reconciler.reconcileScopeCandidates({ organizationId: "org", subjectId: "ana" }); await reconciler.reconcileScopeCandidates({ organizationId: "org", subjectId: "ana" }); assert.equal((await f.dataRepo.listAssignments({ organizationId: "org" })).length, 1); });

test("role revocation invalidates source usability without changing UX membership", async () => { const f = await fixture(); const roleProvider = { async isRolePathActive() { return false; } }; const reconciler = createScopeProjectionReconciler({ dataScopeRepository: f.dataRepo, dataScopeAssignmentService: f.dataSvc, candidateProvider: f.candidateProvider, sourceProvider: createSourceValidationProvider({ organizationStructureRepository: f.orgRepo, roleProvider }), roleProvider, taxonomyPort: taxonomy() }); const result = await reconciler.reconcileScopeCandidates({ organizationId: "org", subjectId: "ana" }); assert.equal(result.created.length, 0); assert.ok(result.errors.length > 0); assert.equal((await f.orgRepo.getMembership(f.membership.id)).status, "active"); });

test("access impact read model and backfill plan are safe and explanatory", async () => { const f = await fixture(); const impact = await createAccessImpactService({ organizationStructureRepository: f.orgRepo, dataScopeRepository: f.dataRepo, candidateProvider: f.candidateProvider }).getAccessImpact({ organizationId: "org", unitId: f.unit.id }); assert.equal(impact.memberships[0].subjectId, "authorized-safe-id"); assert.equal(impact.memberships[0].scopeImpact.projectionStatus, "scope_projection_pending"); const plan = await createBackfillPlanService({ organizationStructureRepository: f.orgRepo, candidateProvider: f.candidateProvider }).checkAndPlan({ organizationId: "org" }); assert.equal(plan.createCandidates.length, 1); assert.ok(plan.planHash); });

test("job payload contract is safe and token-free", () => { const payload = buildReconciliationJobPayload({ operationId: "op", eventId: "evt", organizationId: "org", subjectId: "ana", expectedVersions: { policyVersion: "1" }, reason: "membership_created" }); assert.equal(assertSafeJobPayload(payload), payload); assert.throws(() => assertSafeJobPayload({ ...payload, token: "bearer abc" }), /unsafe_reconciliation_job_payload/); });
