const test=require('node:test'); const assert=require('node:assert/strict');
const { createEventSchemaRegistry, createIntegrationEvent, assertPayloadSafe, classifyError, REASON_CODES, publicOperationReadModel, schemaHash, registryHash }=require('../services/integrationEvents');
function event(overrides={}){return createIntegrationEvent({eventId:'00000000-0000-4000-8000-000000000001',eventType:'operations.operation.started',organizationId:'orgA',aggregate:{type:'operation',id:'op1',version:'1'},actor:{type:'system',serviceId:'worker'},correlation:{correlationId:'corr1'},causation:{},source:{moduleId:'operations',capabilityId:'operations.lifecycle',component:'test'},payload:{operationId:'op1'},...overrides});}
test('IntegrationEvent v1 validates registry, provider-neutral IDs and deterministic hashes',()=>{const registry=createEventSchemaRegistry();const e=event();const v=registry.validate(e,{consumerId:'operations.projection'});assert.equal(v.entry.eventType,e.eventType);assert.match(schemaHash(),/^[a-f0-9]{64}$/);assert.match(registryHash(),/^[a-f0-9]{64}$/);assert.throws(()=>registry.validate(event({eventType:'moodle.course.created'})),{code:REASON_CODES.INVALID});assert.throws(()=>registry.validate(event({eventType:'unknown.event.created'})),{code:REASON_CODES.UNKNOWN_TYPE});assert.throws(()=>registry.validate(e,{consumerId:'other.consumer'}),{code:REASON_CODES.CONSUMER_NOT_ALLOWED});});
test('payload safety rejects secrets, tokens, blobs and accepts governed file references',()=>{assert.doesNotThrow(()=>assertPayloadSafe({file:{fileId:'file1',organizationId:'orgA',ownerModuleId:'operations',mediaType:'text/plain',sensitivity:'internal'}}));assert.throws(()=>assertPayloadSafe({accessToken:'abc'}),{code:REASON_CODES.PAYLOAD_PROHIBITED});assert.throws(()=>assertPayloadSafe({nested:{authorization:'Bearer abc.def.ghi'}}),{code:REASON_CODES.PAYLOAD_PROHIBITED});assert.throws(()=>assertPayloadSafe({blob:'x'.repeat(5000)}),{code:REASON_CODES.PAYLOAD_PROHIBITED});});
test('retry classifier separates retryable and terminal failures',()=>{assert.equal(classifyError(new Error('timeout while publishing')).class,'retryable');assert.equal(classifyError(Object.assign(new Error('bad'),{code:REASON_CODES.PAYLOAD_PROHIBITED})).class,'terminal');});
test('operation public read model is safe and omits queues/secrets/internal rows',()=>{const pub=publicOperationReadModel({id:'op1',operation_type:'sync',module_id:'operations',operation_state:'running',progress_json:{percentage:50},correlation_id:'corr',version:2,queue_name:'private',job_id:'job'});assert.deepEqual(Object.keys(pub).sort(),['acceptedAt','capabilityId','completedAt','correlationId','moduleId','operationId','operationType','problem','progress','queuedAt','result','startedAt','state','version'].sort());assert.equal(pub.queueName,undefined);});

test('payload safety normalizes separated secret key names and reports only paths',()=>{for(const key of ['apiKey','api_key','api-key','privateKey','private_key','client_secret','access-token','authorization','credential','cookie','password','bearer','token']){assert.throws(()=>assertPayloadSafe({nested:{[key]:'super-secret-value'}}),(err)=>err.code===REASON_CODES.PAYLOAD_PROHIBITED && err.details.path===`payload.nested.${key}` && !JSON.stringify(err).includes('super-secret-value'));}});
