"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { createLmsGroupLeadershipService } = require("../lms/groupLeadershipService");
const { createInMemoryEntitlementRepository, createEntitlementService } = require("../authorization/entitlements");
const { createInMemoryDataScopeRepository } = require("../authorization/data-scope");

const roleIdToName = { role_group: "organization_groupleader", role_head: "organization_headteacher", role_teacher: "organization_teacher" };
function runtimePort() { return { async incrementPolicyVersion(){ return 2; }, async enqueueOutbox(){}, async audit(){} }; }
function principal(scopes = ["lms.groups.read", "lms.group_members.read", "lms.course_offerings.read"]) { return { subject: "ana", scopes: new Set(scopes), rolePaths: [{ rolePathId: "group", logtoRoleId: "role_group", canonicalRoleId: "organization_groupleader", roleNameCache: "organization_groupleader", roleKey: "organization_groupleader", membershipId: "membership_group", tokenScopePresent: true }, { rolePathId: "head", logtoRoleId: "role_head", canonicalRoleId: "organization_headteacher", roleNameCache: "organization_headteacher", roleKey: "organization_headteacher", membershipId: "membership_head", tokenScopePresent: true }, { rolePathId: "teacher", logtoRoleId: "role_teacher", canonicalRoleId: "organization_teacher", roleNameCache: "organization_teacher", roleKey: "organization_teacher", membershipId: "membership_teacher", tokenScopePresent: true }] }; }
function repo({ candidates = [] } = {}) { const groups = [{ id: "7b", organizationId: "org", stableKey: "7B", displayName: "7B", unitId: "unit-7b", status: "active" }, { id: "7a", organizationId: "org", stableKey: "7A", displayName: "7A", unitId: "unit-7a", status: "active" }, { id: "8b", organizationId: "org", stableKey: "8B", displayName: "8B", unitId: "unit-8b", status: "active" }]; return { async listLeadershipCandidates(input) { return candidates.map((candidate) => ({ organizationId: "org", subjectId: "ana", capability: "lms", logtoRoleId: input.logtoRoleId, ...candidate })); }, async listGroupsByIds({ groupIds }) { return groups.filter((g) => groupIds.includes(g.id) || groupIds.includes(g.unitId) || groupIds.includes(g.stableKey)); }, async getGroup({ organizationId, groupId }) { return groups.find((g) => g.organizationId === organizationId && [g.id, g.stableKey].includes(groupId)) || null; }, async listMembers({ groupId }) { return [{ id: `student-${groupId}`, memberRef: `student-${groupId}`, displayName: `Student ${groupId}`, memberType: "student" }]; }, async listCourseOfferings({ groupId }) { return [{ id: `course-${groupId}`, courseRef: `math-${groupId}`, displayName: `Math ${groupId}` }]; } }; }
async function seededEntitlements(permissions = ["lms.groups.read", "lms.group_members.read", "lms.course_offerings.read"]) { const repository = createInMemoryEntitlementRepository(); const service = createEntitlementService({ repository, runtimeConsistencyPort: runtimePort(), roleIdToName }); for (const permission of permissions) await service.upsertOwnerLimits({ organizationId: "org", expectedPolicyVersion: await repository.getPolicyVersion("org"), actorLogtoUserId: "owner", changes: [{ logtoRoleId: "role_group", permission, allowed: true }] }); for (const permission of permissions) await service.upsertTenantActivations({ organizationId: "org", expectedPolicyVersion: await repository.getPolicyVersion("org"), actorLogtoUserId: "admin", changes: [{ logtoRoleId: "role_group", permission, enabled: true }] }); return repository; }

const leads7b = { candidateId: "lead-7b", membershipId: "membership_group", canonicalRoleId: "organization_groupleader", unitId: "7b", source: { relationshipType: "leads", id: "rel-7b" }, validFrom: "2026-01-01T00:00:00Z" };

test("Group Leader with ceiling activation and leads relationship sees exactly led group and members", async () => { const entitlementRepository = await seededEntitlements(); const svc = createLmsGroupLeadershipService({ entitlementRepository, dataScopeRepository: createInMemoryDataScopeRepository(), groupRepository: repo({ candidates: [leads7b, { ...leads7b, candidateId: "manage-8b", unitId: "8b", source: { relationshipType: "manages" } }, { ...leads7b, candidateId: "other", organizationId: "other", unitId: "7a" }] }), roleIdToName }); const list = await svc.listGroups({ organizationId: "org", principal: principal() }); assert.deepEqual(list.groups.map((g) => g.id), ["7b"]); const detail = await svc.getGroupDetail({ organizationId: "org", groupId: "7b", principal: principal() }); assert.equal(detail.group.courseOfferings[0].id, "course-7b"); const members = await svc.listGroupMembers({ organizationId: "org", groupId: "7b", principal: principal() }); assert.equal(members.members[0].id, "student-7b"); await assert.rejects(() => svc.getGroupDetail({ organizationId: "org", groupId: "8b", principal: principal() }), /allowed|data_scope_assignment_missing/); });

test("Group Leader denies without ceiling activation or leads scope and never borrows other role fragments", async () => { const emptyEntitlements = createInMemoryEntitlementRepository(); const noPbac = createLmsGroupLeadershipService({ entitlementRepository: emptyEntitlements, dataScopeRepository: createInMemoryDataScopeRepository(), groupRepository: repo({ candidates: [leads7b] }), roleIdToName }); await assert.rejects(() => noPbac.listGroups({ organizationId: "org", principal: principal() }), /owner_ceiling_missing/); const entitlementRepository = await seededEntitlements(["lms.groups.read"]); const noScope = createLmsGroupLeadershipService({ entitlementRepository, dataScopeRepository: createInMemoryDataScopeRepository(), groupRepository: repo({ candidates: [] }), roleIdToName }); await assert.rejects(() => noScope.listGroups({ organizationId: "org", principal: principal(["lms.groups.read"]) }), /data_scope_assignment_missing/); const update = createLmsGroupLeadershipService({ entitlementRepository, dataScopeRepository: createInMemoryDataScopeRepository(), groupRepository: repo({ candidates: [leads7b] }), roleIdToName }); await assert.rejects(() => update.listGroups({ organizationId: "org", principal: principal(["lms.grades.update"]), permission: "lms.grades.update" }), /role_permission_missing|permission_missing|data_scope_required/); });
