const test = require('node:test'); const assert = require('node:assert/strict');
const { createPlanningRuntimeTransportAdapter } = require('../planning/infrastructure/transportAdapter');
const { createHmacModuleExecutionContextIssuer } = require('../planning/infrastructure/moduleExecutionContext');
const { createStaticServiceIdentityProvider } = require('../planning/infrastructure/serviceIdentity');
const { createFakeFederatedPlanningRuntime } = require('../planning/testing/fakeFederatedRuntime');
const { DEFAULT_POLICY } = require('../planning/infrastructure/resiliencePolicy');
const { toRfc9457Problem } = require('../planning/presentation/problemMapper');
function deps(scenario='success'){ const fake=createFakeFederatedPlanningRuntime({ scenario }); const binding={ id:'bind-1', version:7, logtoOrganizationId:'org-A', moduleId:'planning', runtimeId:'rt-1', selectedContractVersion:'planning-runtime/v1', status:'bound', isExecutable:true, organizationModuleId:'mv-1' }; const runtime={ id:'rt-1', runtimeId:'rt-1', moduleId:'planning', runtimeContractVersion:'planning-runtime/v1', runtimeStatus:'available', serviceIdentityRequired:true, expectedAudience:'planning-runtime:test', serviceRef:{ scheme:'civitas-service', name:'planning-runtime', port:8443 }, compatibilityMetadata:{ supportedContracts:['planning-runtime/v1'] } }; const circuit=new Map(); return { fake, port:createPlanningRuntimeTransportAdapter({ runtimeBindingRepository:{ async listBindings(){return [binding]}, async getRuntimeById(){return runtime} }, compatibilityRepository:{ async getCompatibility(){return { compatibilityStatus:'compatible' }} }, moduleExecutionContextIssuer:createHmacModuleExecutionContextIssuer({ secret:'test-secret', ttlMs:30000 }), serviceIdentityProvider:createStaticServiceIdentityProvider({ identity:'spiffe://civitas/gateway', credentialVersion:'cred-v1', allowedAudiences:['planning-runtime:test'] }), transportClient:fake, circuitStatePort:{ async readCircuitState(q){return circuit.get(q.targetBindingId)||null}, async writeCircuitState(s){circuit.set(s.targetBindingId,s); return s;} }, logger:{ info(){}, warn(){}, error(){} }, metrics:{ increment(){} }, resiliencePolicy:{ ...DEFAULT_POLICY, totalDeadlineMs:1000, responseTimeoutMs:500, maxAttempts:2, baseBackoffMs:1 } }) }; }
function ctx(over={}){ return { organizationId:'org-A', subjectId:'sub-1', clientId:'client-1', operation:{ moduleId:'planning', capabilityId:'planning.plans', operationId:'planning.plans.create', actionId:'planning.plans.create', permission:'planning.plans.manage', executionKind:'write' }, authorizationDecision:{ decisionId:'authz-1', authorizationSnapshotVersion:'1', organizationId:'org-A' }, availabilityDecision:{ decisionId:'avail-1', version:'1', executable:true, runtimeBindingVersion:'7', compatibilityVersion:'cmp-1' }, correlationId:'corr-1', idempotency:{ key:'idem-key', requestFingerprint:'fp-1' }, deadline:new Date(Date.now()+5000).toISOString(), ...over }; }
test('PlanningRemoteApplicationPort uses named methods and maps provider-neutral DTOs through private runtime', async()=>{ const { port, fake }=deps(); assert.equal(typeof port.createPlan,'function'); assert.equal(port.execute, undefined); const res=await port.createPlan({ title:'Annual plan' }, ctx()); assert.equal(res.ok,true); assert.equal(res.value.planId,'plan-1'); assert.equal(res.runtimeContractVersion,'planning-runtime/v1'); assert.equal(fake.calls[0].headers.Authorization, undefined); assert.equal(fake.calls[0].headers.Cookie, undefined); assert.equal(fake.calls[0].headers['Idempotency-Key'], 'idem-key'); });
test('forbidden idempotency and operation mismatch fail closed before network', async()=>{ const { port, fake }=deps(); const read=ctx({ operation:{ moduleId:'planning', capabilityId:'planning.plans', operationId:'planning.plans.list', actionId:'planning.plans.read', permission:'planning.plans.read', executionKind:'read' }, idempotency:{ key:'bad', requestFingerprint:'fp' }}); const res=await port.listPlans({}, read); assert.equal(res.ok,false); assert.equal(fake.calls.length,0); });
test('conflict maps to typed problem and RFC 9457 without raw remote body', async()=>{ const { port }=deps('conflict'); const c=ctx({ concurrency:{ etag:'v1' } }); const res=await port.createPlan({ title:'Annual plan' }, c); assert.equal(res.ok,false); assert.equal(res.problem.code,'planning.remote.conflict'); const pub=toRfc9457Problem(res.problem); assert.equal(pub.status,409); assert.equal(JSON.stringify(pub).includes('hostname'), false); });
test('connection reset retries bounded with same idempotency key', async()=>{ const { port, fake }=deps('connection_reset'); const res=await port.createPlan({ title:'Annual plan' }, ctx()); assert.equal(res.ok,false); assert.equal(fake.calls.length,2); assert.equal(fake.calls[0].headers['Idempotency-Key'], fake.calls[1].headers['Idempotency-Key']); });
test('wrong audience is rejected by fake runtime and normalized safely', async()=>{ const d=deps(); d.fake.setScenario('wrong_audience'); const res=await d.port.createPlan({ title:'x' }, ctx()); assert.equal(res.ok,false); assert.match(res.problem.code,/bad_gateway|authorization_context|unavailable/); });
