const { createHmac, timingSafeEqual } = require('node:crypto');
const CONTEXT_VERSION='civitas-module-execution-context/v1';
const SENSITIVE_KEY=/token|secret|password|authorization(?!Decision|Snapshot)|bearer|cookie|headers/i;
function assertNoSensitiveContext(value,path='context'){
  if(Array.isArray(value)) return value.forEach((v,i)=>assertNoSensitiveContext(v,`${path}[${i}]`));
  if(value&&typeof value==='object') for(const [k,v] of Object.entries(value)){ if(SENSITIVE_KEY.test(k)) throw new Error(`${path}.${k} is not allowed in module execution context`); assertNoSensitiveContext(v,`${path}.${k}`); }
  if(typeof value==='string' && /bearer\s+|user:pass|authorization:/i.test(value)) throw new Error(`${path} contains sensitive value`);
}
function sign(secret,encoded){ return createHmac('sha256',secret).update(encoded).digest('base64url'); }
function safeEqual(a,b){ const aa=Buffer.from(String(a||'')); const bb=Buffer.from(String(b||'')); return aa.length===bb.length && timingSafeEqual(aa,bb); }
function createHmacModuleExecutionContextIssuer({ secret, ttlMs=30000, issuer='civitas-runtime-control-plane', clock=()=>new Date() }={}){ if(!secret) throw new Error('ModuleExecutionContext issuer requires signing secret'); return { async issue(input){ assertNoSensitiveContext(input); const issuedAt=clock().toISOString(); const expiresAt=new Date(new Date(issuedAt).getTime()+ttlMs).toISOString(); const payload={ version:CONTEXT_VERSION, issuer, issuedAt, expiresAt, organizationId:input.organizationId, subjectId:input.subjectId, clientId:input.clientId, audience:input.audience, runtimeId:input.runtimeId, moduleId:input.moduleId||input.operation?.moduleId, contractVersion:input.contractVersion, operation:input.operation, authorizationDecision:{ decisionId:input.authorizationDecision?.decisionId, authorizationSnapshotVersion:input.authorizationDecision?.authorizationSnapshotVersion, organizationId:input.authorizationDecision?.organizationId }, availabilityDecision:{ decisionId:input.availabilityDecision?.decisionId, version:input.availabilityDecision?.version, runtimeBindingVersion:input.availabilityDecision?.runtimeBindingVersion, compatibilityVersion:input.availabilityDecision?.compatibilityVersion }, idempotency:input.idempotency ? { key:input.idempotency.key, requestFingerprint:input.idempotency.requestFingerprint } : null, correlationId:input.correlationId, causationId:input.causationId||null }; const encoded=Buffer.from(JSON.stringify(payload)).toString('base64url'); const sig=sign(secret,encoded); return { serialized:`${encoded}.${sig}`, expiresAt, version:CONTEXT_VERSION, audience:input.audience, payload }; } }; }
function createHmacModuleExecutionContextValidator({ secret, clock=()=>new Date() }={}){ if(!secret) throw new Error('ModuleExecutionContext validator requires signing secret'); return { validate(serialized, expected={}){ const [encoded,sig,extra]=String(serialized||'').split('.'); if(!encoded||!sig||extra!==undefined) return { ok:false, reason:'malformed' }; const good=sign(secret,encoded); if(!safeEqual(sig,good)) return { ok:false, reason:'invalid_signature' }; let payload; try { payload=JSON.parse(Buffer.from(encoded,'base64url').toString('utf8')); } catch { return { ok:false, reason:'schema_invalid' }; } if(payload.version!==CONTEXT_VERSION) return { ok:false, reason:'wrong_version' }; for(const k of ['issuer','organizationId','audience','runtimeId','moduleId','contractVersion','correlationId']) if(expected[k] && payload[k]!==expected[k]) return { ok:false, reason:`wrong_${k}` }; if(new Date(payload.expiresAt).getTime() <= clock().getTime()) return { ok:false, reason:'expired' }; return { ok:true, payload }; } }; }
module.exports={ CONTEXT_VERSION, createHmacModuleExecutionContextIssuer, createHmacModuleExecutionContextValidator, assertNoSensitiveContext };
