const { createPlanningRemoteApplicationPort, assertPlanningRemoteCallContext, NAMED_USE_CASES, ok, failed, problem, REMOTE_PROBLEM_CODES } = require('../application/remotePort');
const { CONTRACT_VERSION, MEDIA_TYPE, toWireRequest, fromWireResponse, normalizeProblem } = require('./runtimeContractV1');
const { DEFAULT_POLICY, canRetry, backoffMs } = require('./resiliencePolicy');
const { selectPlanningRuntimeContractVersion } = require('./versionNegotiator');
function safeServiceRef(ref){ if(!ref || typeof ref !== 'object') return false; if(ref.scheme !== 'civitas-service') return false; if(/[/?#@]/.test(ref.name||'') || String(ref.name).length>128) return false; if(ref.port && (ref.port<1 || ref.port>65535)) return false; return true; }
function circuitKey(ctx,binding,version){ return `${ctx.organizationId}|planning|${binding.id}|${version}|${ctx.operation.capabilityId}`; }
class BindingBulkhead { constructor(limit){ this.limit=limit; this.inFlight=new Map(); } acquire(key){ const n=this.inFlight.get(key)||0; if(n>=this.limit) return false; this.inFlight.set(key,n+1); return true; } release(key){ this.inFlight.set(key,Math.max(0,(this.inFlight.get(key)||1)-1)); } }
function createPlanningRuntimeTransportAdapter(deps){ for(const k of ['runtimeBindingRepository','compatibilityRepository','moduleExecutionContextIssuer','serviceIdentityProvider','transportClient','circuitStatePort','logger','metrics']) if(!deps?.[k]) throw new Error(`Planning runtime transport adapter requires ${k}`); const policy=deps.resiliencePolicy||DEFAULT_POLICY; const clock=deps.clock||(()=>new Date()); const bulkhead=new BindingBulkhead(policy.bulkhead.maxInFlightPerBinding);
  async function invoke(useCase,input,context){ try{ assertPlanningRemoteCallContext(context,useCase); }catch(e){ return failed(problem(REMOTE_PROBLEM_CODES.AUTH_CONTEXT,'authorization_context',{ correlationId:context?.correlationId, decisionId:context?.authorizationDecision?.decisionId }), context?.correlationId); }
    const binding=(await deps.runtimeBindingRepository.listBindings({ logtoOrganizationId:context.organizationId, moduleId:'planning' })).find(b=>b.isExecutable && b.status==='bound' && String(b.version)===String(context.availabilityDecision.runtimeBindingVersion));
    if(!binding) return failed(problem(REMOTE_PROBLEM_CODES.UNAVAILABLE,'runtime_unavailable',{ correlationId:context.correlationId, retryable:true }), context.correlationId);
    const runtime=deps.runtimeBindingRepository.getRuntimeByDatabaseId ? await deps.runtimeBindingRepository.getRuntimeByDatabaseId(binding.runtimeId) : await deps.runtimeBindingRepository.getRuntimeByRuntimeId(binding.runtimeId); if(!runtime || runtime.moduleId!=='planning' || runtime.runtimeId!==context.availabilityDecision.runtimeId && context.availabilityDecision.runtimeId || !runtime.serviceIdentityRequired || !safeServiceRef(runtime.serviceRef) || runtime.runtimeStatus!=='available') return failed(problem(REMOTE_PROBLEM_CODES.UNAVAILABLE,'runtime_unavailable',{ correlationId:context.correlationId, retryable:true }), context.correlationId);
    const compat=await deps.compatibilityRepository.getCompatibility({ moduleVersionId:binding.organizationModuleId || binding.moduleVersionId, runtimeId:binding.runtimeId }) || { compatibilityStatus:'compatible' };
    const selected=selectPlanningRuntimeContractVersion({ bindingVersion:binding.selectedContractVersion, runtimeSupported:runtime.compatibilityMetadata?.supportedContracts||[runtime.runtimeContractVersion], compatibilityStatus:compat.compatibilityStatus });
    if(!selected.ok) return failed(problem(REMOTE_PROBLEM_CODES.CONTRACT_MISMATCH,'contract_mismatch',{ correlationId:context.correlationId, retryable:false }), context.correlationId);
    const ck=circuitKey(context,binding,selected.version); const circuit=await deps.circuitStatePort.readCircuitState({ organizationId:context.organizationId, targetType:'module_runtime_binding', targetBindingId:ck }); if(circuit?.state==='open') return failed(problem(REMOTE_PROBLEM_CODES.UNAVAILABLE,'runtime_unavailable',{ correlationId:context.correlationId, retryable:true }), context.correlationId);
    if(!bulkhead.acquire(ck)) return failed(problem(REMOTE_PROBLEM_CODES.BULKHEAD_REJECTED,'runtime_unavailable',{ correlationId:context.correlationId, retryable:true }), context.correlationId);
    try { let executionContext; let identity; try { executionContext=await deps.moduleExecutionContextIssuer.issue({ ...context, audience:runtime.expectedAudience, runtimeId:runtime.runtimeId, moduleId:'planning', contractVersion:selected.version }); identity=await deps.serviceIdentityProvider.getIdentity({ audience:runtime.expectedAudience, runtimeBindingId:binding.id, runtimeId:runtime.runtimeId, moduleId:'planning', organizationId:context.organizationId, contractVersion:selected.version }); } catch { return failed(problem(REMOTE_PROBLEM_CODES.AUTH_CONTEXT,'authorization_context',{ correlationId:context.correlationId }), context.correlationId); } const wire=toWireRequest(useCase,input,context); const bytes=Buffer.byteLength(JSON.stringify(wire)); if(bytes>policy.maximumRequestBytes) return failed(problem(REMOTE_PROBLEM_CODES.BAD_GATEWAY,'payload_too_large',{ correlationId:context.correlationId }), context.correlationId);
      const headers={ 'Content-Type':MEDIA_TYPE, Accept:MEDIA_TYPE, 'X-Civitas-Contract-Version':CONTRACT_VERSION, 'X-Civitas-Execution-Context':executionContext.serialized, 'X-Correlation-Id':context.correlationId }; if(context.causationId) headers['X-Causation-Id']=context.causationId; if(context.idempotency?.key) headers['Idempotency-Key']=context.idempotency.key; if(context.concurrency?.etag || context.concurrency?.expectedVersion) headers['If-Match']=context.concurrency.etag||context.concurrency.expectedVersion;
      let attempt=1; const started=clock().getTime(); while(true){ const remaining=Math.min(policy.totalDeadlineMs, context.deadline ? new Date(context.deadline).getTime()-clock().getTime() : policy.totalDeadlineMs) - (clock().getTime()-started); if(remaining<=0 || new Date(executionContext.expiresAt).getTime()-clock().getTime()<remaining) return failed(problem(REMOTE_PROBLEM_CODES.TIMEOUT,'runtime_timeout',{ correlationId:context.correlationId, retryable:true }), context.correlationId); const res=await deps.transportClient.send({ serviceRef:runtime.serviceRef, path:require('./runtimeContractV1').paths[useCase], method:'POST', headers, body:wire, serviceIdentity:identity, timeoutMs:Math.min(remaining,policy.responseTimeoutMs) }).catch(e=>({ status:0, transportError:e.code||'connection_reset' })); if(res.status>=200 && res.status<300){ const responseBytes=Buffer.byteLength(JSON.stringify(res.body||{})); if(responseBytes>policy.maximumResponseBytes) return failed(problem(REMOTE_PROBLEM_CODES.BAD_GATEWAY,'response_too_large',{ correlationId:context.correlationId, retryable:false }), context.correlationId); let value; try { value=fromWireResponse(useCase,res.body); } catch { return failed(problem(REMOTE_PROBLEM_CODES.BAD_GATEWAY,'runtime_schema_invalid',{ correlationId:context.correlationId, retryable:false }), context.correlationId); } await deps.circuitStatePort.writeCircuitState({ organizationId:context.organizationId, targetType:'module_runtime_binding', targetBindingId:ck, moduleId:'planning', capabilityId:context.operation.capabilityId, state:'closed', provenance:{ source:'planning-runtime-transport', reasonCode:'success' } }); return ok(value,{ runtimeContractVersion:selected.version, runtimeBindingVersion:String(binding.version), correlationId:context.correlationId, remoteRequestId:res.headers?.['x-runtime-request-id'] }); }
        const retry=canRetry({ executionKind:context.operation.executionKind, idempotency:context.idempotency, status:res.status, transportError:res.transportError, attempt, policy }); if(!retry){ const p=res.status?normalizeProblem(res.status,res.body,context.correlationId):problem(REMOTE_PROBLEM_CODES.UNAVAILABLE,'runtime_unavailable',{ correlationId:context.correlationId, retryable:true }); await deps.circuitStatePort.writeCircuitState({ organizationId:context.organizationId, targetType:'module_runtime_binding', targetBindingId:ck, moduleId:'planning', capabilityId:context.operation.capabilityId, state:[502,503,504,0].includes(res.status)?'open':'closed', provenance:{ source:'planning-runtime-transport', reasonCode:p.code } }); return failed(p,context.correlationId); } deps.metrics.increment?.('planning_gateway_retry_count',{moduleId:'planning',capabilityId:context.operation.capabilityId,operationId:context.operation.operationId,runtimeContractVersion:selected.version,outcome:'retry',circuitState:circuit?.state||'closed'}); await new Promise(r=>setTimeout(r,backoffMs(attempt,policy))); attempt++; }
    } finally { bulkhead.release(ck); }
  }
  return createPlanningRemoteApplicationPort(Object.fromEntries(Object.keys(NAMED_USE_CASES).map(m=>[m,(input,ctx)=>invoke(m,input,ctx)])));
}
function createProductionPlanningRemoteApplicationPort(deps){ return createPlanningRuntimeTransportAdapter(deps); }
module.exports={ createPlanningRuntimeTransportAdapter, createProductionPlanningRemoteApplicationPort, safeServiceRef };
