const { randomUUID, createHash } = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const ENVELOPE_VERSION='civitas-integration-event/v1';
const MAX_PAYLOAD_BYTES=16384;
const OUTBOX_STATES=Object.freeze({PENDING:'pending',CLAIMED:'claimed',RETRY_SCHEDULED:'retry_scheduled',PUBLISHED:'published',TERMINAL_FAILED:'terminal_failed',DEAD_LETTERED:'dead_lettered',CANCELLED:'cancelled'});
const INBOX_STATES=Object.freeze({RECEIVED:'received',PROCESSING:'processing',PROCESSED:'processed',RETRYABLE_FAILED:'retryable_failed',TERMINAL_FAILED:'terminal_failed',DEAD_LETTERED:'dead_lettered'});
const OPERATION_STATES=Object.freeze({ACCEPTED:'accepted',QUEUED:'queued',RUNNING:'running',SUCCEEDED:'succeeded',PARTIALLY_SUCCEEDED:'partially_succeeded',FAILED:'failed',CANCELLED:'cancelled'});
const REASON_CODES=Object.freeze({INVALID:'integration_event_invalid',UNKNOWN_TYPE:'integration_event_unknown_type',UNSUPPORTED_VERSION:'integration_event_unsupported_version',PAYLOAD_TOO_LARGE:'integration_event_payload_too_large',PAYLOAD_PROHIBITED:'integration_event_payload_prohibited',TENANT_MISSING:'integration_event_tenant_missing',TENANT_MISMATCH:'integration_event_tenant_mismatch',CONSUMER_NOT_ALLOWED:'integration_event_consumer_not_allowed',OUTBOX_CLAIM_CONFLICT:'integration_outbox_claim_conflict',OUTBOX_RETRYABLE:'integration_outbox_publish_retryable',OUTBOX_TERMINAL:'integration_outbox_publish_terminal',ATTEMPTS_EXHAUSTED:'integration_outbox_attempts_exhausted',INBOX_DUPLICATE:'integration_inbox_duplicate',INBOX_PROCESSING:'integration_inbox_processing',INBOX_RECONCILIATION:'integration_inbox_reconciliation_required',DEAD_LETTERED:'integration_dead_lettered',OPERATION_TRANSITION_INVALID:'operation_transition_invalid',OPERATION_VERSION_CONFLICT:'operation_version_conflict',OPERATION_WRONG_TENANT:'operation_wrong_tenant'});
const TERMINAL_OPERATION_STATES=new Set([OPERATION_STATES.SUCCEEDED,OPERATION_STATES.PARTIALLY_SUCCEEDED,OPERATION_STATES.FAILED,OPERATION_STATES.CANCELLED]);
const TRANSITIONS=Object.freeze({accepted:['queued','cancelled','failed'],queued:['running','cancelled','failed'],running:['succeeded','partially_succeeded','failed','cancelled'],succeeded:[],partially_succeeded:[],failed:[],cancelled:[]});
class IntegrationEventError extends Error{constructor(code,message,details={}){super(message);this.name='IntegrationEventError';this.code=code;this.details=details;}}
const REPO_ROOT=path.resolve(__dirname,'..','..');
function contractPath(...parts){return path.join(REPO_ROOT,...parts);}
function hashFile(file){return createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function schemaHash(){return hashFile(contractPath('contracts','integration','integration-event-v1.schema.json'));}
function registryHash(){return hashFile(contractPath('contracts','integration','integration-event-registry.json'));}
function bytes(value){return Buffer.byteLength(JSON.stringify(value||{}));}
function normalizePayloadKey(key){return String(key).replace(/[^a-z0-9]/gi,'').toLowerCase();}
function hasBadKey(key){return /secret|password|token|apikey|authorization|bearer|privatekey|credential|cookie/.test(normalizePayloadKey(key));}
function hasBadValue(value){return typeof value==='string' && (/bearer\s+/i.test(value)||/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(value)||/\w+:\w+@/.test(value)||value.length>4096);}
function assertPayloadSafe(value,path='payload'){ if(bytes(value)>MAX_PAYLOAD_BYTES) throw new IntegrationEventError(REASON_CODES.PAYLOAD_TOO_LARGE,'payload too large',{path}); if(Array.isArray(value)) return value.forEach((v,i)=>assertPayloadSafe(v,`${path}[${i}]`)); if(value&&typeof value==='object'){ for(const [k,v] of Object.entries(value)){ if(hasBadKey(k)||hasBadValue(v)) throw new IntegrationEventError(REASON_CODES.PAYLOAD_PROHIBITED,'payload contains prohibited data',{path:`${path}.${k}`}); assertPayloadSafe(v,`${path}.${k}`); } } }
function loadRegistry(){return JSON.parse(fs.readFileSync(contractPath('contracts','integration','integration-event-registry.json'),'utf8'));}
function createEventSchemaRegistry(entries=loadRegistry().events){const map=new Map(entries.map(e=>[`${e.eventType}|${e.schemaVersion}`,e]));return{get(eventType,schemaVersion){return map.get(`${eventType}|${schemaVersion}`)||null},list(){return [...map.values()]},validate(event,{consumerId}={}){const orgId=event?.organizationId||event?.organization_id; if(!orgId)throw new IntegrationEventError(REASON_CODES.TENANT_MISSING,'organization_id required'); if(/^(moodle|agora|stripe|matomo|bullmq|redis)\./i.test(event.eventType))throw new IntegrationEventError(REASON_CODES.INVALID,'provider event type rejected'); const entry=this.get(event.eventType,event.schemaVersion); if(!entry)throw new IntegrationEventError(REASON_CODES.UNKNOWN_TYPE,'unknown event type'); if(entry.lifecycle==='removed')throw new IntegrationEventError(REASON_CODES.UNSUPPORTED_VERSION,'removed event version'); if(consumerId&&!(entry.allowedConsumers||[]).includes(consumerId))throw new IntegrationEventError(REASON_CODES.CONSUMER_NOT_ALLOWED,'consumer not allowed'); assertPayloadSafe(event.payload); return Object.freeze({event,entry});}}}
function createIntegrationEvent(input){const event={eventId:input.eventId||randomUUID(),eventType:input.eventType,schemaVersion:input.schemaVersion||ENVELOPE_VERSION,occurredAt:input.occurredAt||new Date().toISOString(),organizationId:input.organizationId||input.organization_id,aggregate:input.aggregate,actor:input.actor||{type:'system'},correlation:input.correlation||{correlationId:input.correlationId||randomUUID()},causation:input.causation||{},source:input.source,sensitivity:input.sensitivity||'internal',payload:input.payload||{}}; for(const k of ['eventId','eventType','schemaVersion','occurredAt','organizationId','aggregate','actor','correlation','causation','source','sensitivity','payload']) if(event[k]==null) throw new IntegrationEventError(REASON_CODES.INVALID,`missing ${k}`); assertPayloadSafe(event.payload); return Object.freeze(event);}
function classifyError(err){if(err instanceof IntegrationEventError){return ['integration_event_payload_prohibited','integration_event_invalid','integration_event_unknown_type','integration_event_consumer_not_allowed'].includes(err.code)?{class:'terminal',reasonCode:err.code}:{class:'reconciliation_required',reasonCode:err.code};} if(/timeout|ECONNRESET|temporarily|429|5\d\d/i.test(err?.message||''))return{class:'retryable',reasonCode:REASON_CODES.OUTBOX_RETRYABLE}; return{class:'terminal',reasonCode:REASON_CODES.OUTBOX_TERMINAL};}
function backoff(attempt,{baseMs=1000,maxMs=60000}={}){return Math.min(maxMs,baseMs*Math.pow(2,Math.max(0,attempt-1)));}
function publicOperationReadModel(op){return{operationId:op.id||op.operationId,operationType:op.operation_type||op.operationType,moduleId:op.module_id||op.moduleId,capabilityId:op.capability_id||op.capabilityId,state:op.operation_state||op.state,progress:op.progress_json||op.progress||{},result:op.result_json||op.result||null,problem:op.problem_json||op.problem||null,correlationId:op.correlation_id||op.correlationId,acceptedAt:op.accepted_at||op.acceptedAt,queuedAt:op.queued_at||op.queuedAt,startedAt:op.started_at||op.startedAt,completedAt:op.completed_at||op.completedAt,version:op.version};}
function createPostgresIntegrationRepository({pool,clock=()=>new Date(),registry=createEventSchemaRegistry()}={}){if(!pool)throw new Error('pool is required');const now=()=>clock().toISOString();return{
 async appendEvent(event){const e=createIntegrationEvent(event); registry.validate(e); const r=await pool.query(`insert into integration_outbox_events(event_id,event_type,schema_version,logto_organization_id,aggregate_type,aggregate_id,aggregate_version,actor_json,correlation_id,trace_id,causation_id,parent_event_id,operation_id,source_json,sensitivity,payload) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) returning *`,[e.eventId,e.eventType,e.schemaVersion,e.organizationId,e.aggregate.type,e.aggregate.id,e.aggregate.version||null,e.actor,e.correlation.correlationId,e.correlation.traceId||null,e.causation.causationId||null,e.causation.parentEventId||null,e.causation.operationId||null,e.source,e.sensitivity,e.payload]);return r.rows[0]},
 async claimBatch({limit=10,leaseOwner='dispatcher',leaseSeconds=30}={}){const r=await pool.query(`with picked as (select id from integration_outbox_events where (state in ('pending','retry_scheduled') and next_attempt_at<=now()) or (state='claimed' and lease_expires_at<=now()) order by created_at for update skip locked limit $1) update integration_outbox_events o set state='claimed', lease_owner=$2, lease_expires_at=now()+($3||' seconds')::interval, attempt_count=attempt_count+1, version=version+1, updated_at=now() from picked where o.id=picked.id returning o.*`,[limit,leaseOwner,String(leaseSeconds)]);return r.rows},
 async markPublished({eventId}){const r=await pool.query(`update integration_outbox_events set state='published', published_at=now(), lease_owner=null, lease_expires_at=null, version=version+1, updated_at=now() where event_id=$1 and state='claimed' returning *`,[eventId]);return r.rows[0]},
 async scheduleRetry({eventId,error,delayMs}){const c=classifyError(error);const client=await pool.connect();try{await client.query('begin');const r=await client.query(`update integration_outbox_events set state=case when attempt_count>=max_attempts then 'dead_lettered' else 'retry_scheduled' end, next_attempt_at=now()+($2||' milliseconds')::interval, lease_owner=null, lease_expires_at=null, last_error_class=$3, last_error_json=$4, dead_lettered_at=case when attempt_count>=max_attempts then now() else dead_lettered_at end, version=version+1, updated_at=now() where event_id=$1 returning *`,[eventId,String(delayMs||backoff(1)),c.reasonCode,{reasonCode:c.reasonCode}]);const row=r.rows[0];if(row&&row.state==='dead_lettered'){await client.query(`insert into integration_dead_letters(source_kind,source_id,event_id,event_type,schema_version,logto_organization_id,producer,consumer_id,attempt_count,terminal_reason_code,failure_json,correlation_id,causation_id) values('outbox',$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[row.id,row.event_id,row.event_type,row.schema_version,row.logto_organization_id,row.source_json?.component||null,null,row.attempt_count,c.reasonCode,{reasonCode:c.reasonCode},row.correlation_id,row.causation_id]);}await client.query('commit');return row;}catch(err){await client.query('rollback');throw err;}finally{client.release();}},
 async moveToDeadLetter({eventId,consumerId=null,reasonCode=REASON_CODES.DEAD_LETTERED}){const client=await pool.connect();try{await client.query('begin');const r=await client.query(`update integration_outbox_events set state='dead_lettered', dead_lettered_at=now(), last_error_class=$2, version=version+1 where event_id=$1 returning *`,[eventId,reasonCode]);const row=r.rows[0]; if(row) await client.query(`insert into integration_dead_letters(source_kind,source_id,event_id,event_type,schema_version,logto_organization_id,producer,consumer_id,attempt_count,terminal_reason_code,failure_json,correlation_id,causation_id) values('outbox',$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[row.id,row.event_id,row.event_type,row.schema_version,row.logto_organization_id,row.source_json?.component||null,consumerId,row.attempt_count,reasonCode,{reasonCode},row.correlation_id,row.causation_id]);await client.query('commit');return row;}catch(err){await client.query('rollback');throw err;}finally{client.release();}},
 async findByEventId({organizationId,eventId}){const r=await pool.query('select * from integration_outbox_events where logto_organization_id=$1 and event_id=$2',[organizationId,eventId]);return r.rows[0]||null},
 async releaseExpiredClaims(){const r=await pool.query(`update integration_outbox_events set state='retry_scheduled', lease_owner=null, lease_expires_at=null, version=version+1 where state='claimed' and lease_expires_at<now() returning *`);return r.rows},
 async claimInbox({consumerId,event,leaseOwner='consumer',leaseSeconds=30}){const e=createIntegrationEvent(event); const attemptLeaseOwner=`${leaseOwner}:${randomUUID()}`; const r=await pool.query(`insert into integration_inbox_receipts(consumer_id,event_id,event_type,schema_version,logto_organization_id,state,attempt_count,lease_owner,lease_expires_at,correlation_id,causation_id) values($1,$2,$3,$4,$5,'processing',1,$6,now()+($7||' seconds')::interval,$8,$9) on conflict(consumer_id,event_id) do update set state=case when integration_inbox_receipts.state='processed' then 'processed' when integration_inbox_receipts.lease_expires_at<=now() then 'processing' else integration_inbox_receipts.state end, attempt_count=case when integration_inbox_receipts.lease_expires_at<=now() then integration_inbox_receipts.attempt_count+1 else integration_inbox_receipts.attempt_count end, lease_owner=case when integration_inbox_receipts.lease_expires_at<=now() then excluded.lease_owner else integration_inbox_receipts.lease_owner end, lease_expires_at=case when integration_inbox_receipts.lease_expires_at<=now() then excluded.lease_expires_at else integration_inbox_receipts.lease_expires_at end, last_received_at=now() returning *`,[consumerId,e.eventId,e.eventType,e.schemaVersion,e.organizationId,attemptLeaseOwner,String(leaseSeconds),e.correlation.correlationId,e.causation.causationId||null]);const row=r.rows[0]; if(row.state==='processed') throw new IntegrationEventError(REASON_CODES.INBOX_DUPLICATE,'duplicate delivery processed',{path:'inbox.receipt'}); if(row.state==='processing'&&row.lease_owner!==attemptLeaseOwner) throw new IntegrationEventError(REASON_CODES.INBOX_PROCESSING,'receipt already processing',{path:'inbox.receipt'}); return row},
 async markInboxProcessed({consumerId,eventId,result={}}){const r=await pool.query(`update integration_inbox_receipts set state='processed', processed_at=now(), result_digest=$3, result_reference=$4, lease_owner=null, lease_expires_at=null, version=version+1 where consumer_id=$1 and event_id=$2 returning *`,[consumerId,eventId,createHash('sha256').update(JSON.stringify(result)).digest('hex'),result.reference||null]);return r.rows[0]},
 async createOperation({organizationId,operationType,moduleId,capabilityId,requestedBy={},correlationId=randomUUID(),causationId=null,input={}}){const r=await pool.query(`insert into operational_operations(logto_organization_id,operation_type,module_id,capability_id,operation_state,status,input_json,requested_by_json,correlation_id,causation_id,accepted_at) values($1,$2,$3,$4,'accepted','queued',$5,$6,$7,$8,now()) returning *`,[organizationId,operationType,moduleId,capabilityId||null,input,requestedBy,correlationId,causationId]);return r.rows[0]},
 async transitionOperation({organizationId,operationId,expectedVersion,toState,principal={},reason,progress={},result=null,problem=null}){const cur=(await pool.query('select * from operational_operations where logto_organization_id=$1 and id=$2 and version=$3',[organizationId,operationId,expectedVersion])).rows[0]; if(!cur) throw new IntegrationEventError(REASON_CODES.OPERATION_VERSION_CONFLICT,'operation version conflict'); if(!(TRANSITIONS[cur.operation_state]||[]).includes(toState)) throw new IntegrationEventError(REASON_CODES.OPERATION_TRANSITION_INVALID,'invalid operation transition',{from:cur.operation_state,to:toState}); const r=await pool.query(`update operational_operations set operation_state=$4::varchar,status=$4::varchar,progress_json=$5,result_json=$6,problem_json=$7,executing_principal_json=$8,queued_at=case when $4::text='queued' then now() else queued_at end,started_at=case when $4::text='running' then now() else started_at end,completed_at=case when $4::text in ('succeeded','partially_succeeded','failed','cancelled') then now() else completed_at end,version=version+1,updated_at=now() where logto_organization_id=$1 and id=$2 and version=$3 returning *`,[organizationId,operationId,expectedVersion,toState,progress,result,problem,principal]);if(!r.rows[0]) throw new IntegrationEventError(REASON_CODES.OPERATION_VERSION_CONFLICT,'operation version conflict'); return r.rows[0]},
 async getOperation({organizationId,operationId}){const r=await pool.query('select * from operational_operations where logto_organization_id=$1 and id=$2',[organizationId,operationId]);return r.rows[0]||null},
 async listForReconciliation({organizationId,state}={}){const r=await pool.query('select * from integration_outbox_events where ($1::text is null or logto_organization_id=$1) and ($2::text is null or state=$2) order by created_at limit 100',[organizationId||null,state||null]);return r.rows}
}}
function createIntegrationDispatcher({repository,registry=createEventSchemaRegistry(),transport,clock=()=>new Date()}={}){if(!repository||!transport)throw new Error('repository and transport are required');return{async dispatchOnce({limit=10,leaseOwner='dispatcher'}={}){const claimed=await repository.claimBatch({limit,leaseOwner});const results=[];for(const row of claimed){const event={eventId:row.event_id,eventType:row.event_type,schemaVersion:row.schema_version,occurredAt:row.created_at.toISOString(),organizationId:row.logto_organization_id,aggregate:{type:row.aggregate_type,id:row.aggregate_id,version:row.aggregate_version},actor:row.actor_json,correlation:{correlationId:row.correlation_id,traceId:row.trace_id},causation:{causationId:row.causation_id,parentEventId:row.parent_event_id,operationId:row.operation_id},source:row.source_json,sensitivity:row.sensitivity,payload:row.payload};try{registry.validate(event);await transport.publish(event);await repository.markPublished({eventId:row.event_id});results.push({eventId:row.event_id,state:'published'});}catch(error){const c=classifyError(error); if(c.class==='retryable') await repository.scheduleRetry({eventId:row.event_id,error}); else await repository.moveToDeadLetter({eventId:row.event_id,reasonCode:c.reasonCode}); results.push({eventId:row.event_id,state:c.class,reasonCode:c.reasonCode});}}return results;}}}
module.exports={ENVELOPE_VERSION,OUTBOX_STATES,INBOX_STATES,OPERATION_STATES,REASON_CODES,IntegrationEventError,createEventSchemaRegistry,createIntegrationEvent,assertPayloadSafe,classifyError,backoff,publicOperationReadModel,createPostgresIntegrationRepository,createIntegrationDispatcher,schemaHash,registryHash};
