const { createHash } = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const LIFECYCLES = Object.freeze(['disabled','provisioning','active','degraded','suspended','decommissioning']);
const COMPATIBLE = new Set(['compatible','deprecated_compatible']);
const EXECUTABLE_BINDING = new Set(['bound']);
const REASON_CODES = Object.freeze({
  INVALID:'MODULE_LIFECYCLE_TRANSITION_INVALID',
  CONFLICT:'MODULE_LIFECYCLE_VERSION_CONFLICT',
  BINDING_CONFLICT:'MODULE_RUNTIME_BINDING_VERSION_CONFLICT',
  MISSING_BINDING:'MODULE_RUNTIME_BINDING_MISSING',
  WRONG_TENANT:'MODULE_RUNTIME_BINDING_WRONG_TENANT',
  WRONG_MODULE:'MODULE_RUNTIME_BINDING_WRONG_MODULE',
  INCOMPATIBLE:'MODULE_RUNTIME_INCOMPATIBLE',
  UNAVAILABLE:'MODULE_RUNTIME_UNAVAILABLE',
  NOT_EXECUTABLE:'MODULE_INSTALLATION_NOT_EXECUTABLE',
  REPOSITORY_REQUIRED:'MODULE_CONTROL_PLANE_REPOSITORY_REQUIRED',
  DUPLICATE_BINDING:'MODULE_RUNTIME_BINDING_DUPLICATE'
});
const TRANSITIONS = Object.freeze({ disabled:['provisioning'], provisioning:['disabled','active','suspended'], active:['degraded','suspended','decommissioning'], degraded:['suspended','active','decommissioning'], suspended:['provisioning','decommissioning'], decommissioning:[] });
const SECRET_RE = /(secret|token|password|api[_-]?key|client[_-]?secret|credential|private[_-]?key|authorization|bearer|jwt)/i;

class ModuleControlPlaneError extends Error { constructor(code, message, details={}){ super(message); this.name='ModuleControlPlaneError'; this.code=code; this.details=details; this.status=code.endsWith('CONFLICT')?409:422; } }
function required(value, name){ if(value===undefined||value===null||value==='') throw new ModuleControlPlaneError('MODULE_CONTROL_PLANE_FIELD_REQUIRED', `${name} is required`, { field:name }); return value; }
function assertNoSecrets(value, root='payload') { const paths=[]; function visit(v,p){ if(v==null) return; if(typeof v==='string'){ if(SECRET_RE.test(p) || /^https?:\/\/[^/?#]+:[^/?#]+@/i.test(v) || /[?&#][^=]*(token|secret|password|api[_-]?key)=/i.test(v) || /\/((eyJ[A-Za-z0-9_-]+\.){2}|sk_(live|test)_)/i.test(v)) paths.push(p); return; } if(typeof v !== 'object') return; for(const [k,c] of Object.entries(v)){ const np=`${p}.${k}`; if(SECRET_RE.test(k) && c!==undefined && c!==null && c!=='') paths.push(np); visit(c,np); } } visit(value,root); if(paths.length) throw new ModuleControlPlaneError('MODULE_SECRET_DETECTED','Secret-like module control plane data rejected',{ paths:[...new Set(paths)] }); }
function hashManifest(m){ return createHash('sha256').update(JSON.stringify(m)).digest('hex'); }
function loadAuthoredCatalog(){ const p=path.join(__dirname,'..','..','contracts','modules','module-catalog.v2.json'); return JSON.parse(fs.readFileSync(p,'utf8')); }
function loadCatalogHash(){ return fs.readFileSync(path.join(__dirname,'..','..','contracts','modules','generated','module-catalog-v2.inventory.sha256'),'utf8').trim(); }
function normalizeActor(input){ return { actorLogtoUserId: required(input.actorLogtoUserId || input.actor, 'actorLogtoUserId'), reason: required(input.reason, 'reason'), correlationId: input.correlationId || null }; }
function lifecycleAllowed(from,to){ return (TRANSITIONS[from]||[]).includes(to); }
function nowIso(clock){ const value=clock(); return value instanceof Date ? value.toISOString() : new Date(value).toISOString(); }
function redactedRuntime(row){ return { ...row, secretsRef: row.secretsRef ? '[redacted-ref]' : null }; }
function isUniqueViolation(error){ return error?.code === '23505'; }

async function writeAudit(tx, event){
  const { schema } = require('../lib/db');
  const table=schema.auditLogs;
  await tx.insert(table).values({
    logtoOrganizationId: event.logtoOrganizationId || null,
    actorLogtoUserId: event.actorLogtoUserId || null,
    actorType: 'system',
    action: event.action,
    targetType: event.targetType || 'module_control_plane',
    targetId: event.targetId || null,
    result: 'success',
    metadata: event.metadata || {}
  });
}
async function writeOutbox(tx, event){
  const { schema } = require('../lib/db');
  const table=schema.operationalOperations;
  await tx.insert(table).values({
    logtoOrganizationId: event.logtoOrganizationId || null,
    operationType: event.type,
    entityType: event.entityType || 'module_control_plane_event',
    entityId: event.entityId || null,
    status: 'pending',
    inputJson: event.payload || {},
    queueName: 'module-control-plane'
  });
}

function createInMemoryModuleControlPlaneRepository(seed={}){
  const catalog=new Map(), versions=new Map(), orgModules=new Map(), runtimes=new Map(), compat=new Map(), bindings=new Map(), audit=[], outbox=[]; let seq=0; const id=(p)=>`${p}-${++seq}`;
  return {
    kind:'in-memory-test-double', audit,outbox,catalog,versions,orgModules,runtimes,compat,bindings,
    async upsertCatalogFromManifest(manifest, provenance={}){ const row={ moduleId:manifest.id, kind:manifest.kind, businessOwner:manifest.ownership.businessOwner, catalogStatus:manifest.status, catalogVersion:seed.catalogVersion||'2.0.0', catalogHash:loadCatalogHash(), provenance }; catalog.set(row.moduleId,row); return row; },
    async publishModuleVersion(manifest, provenance={}){ const key=`${manifest.id}|${manifest.version}`; if(versions.has(key)) return versions.get(key); const row={ id:id('mv'), moduleId:manifest.id, semanticVersion:manifest.version, manifestSchemaVersion:manifest.schemaVersion, manifestHash:hashManifest(manifest), deploymentMode:manifest.deploymentMode, contractStatus:manifest.status, dataOwnership:manifest.dataOwnership, contractRefs:{ contributions:manifest.contributions, federated:manifest.federated||null }, compatibilityPolicy:manifest.compatibility.policy, manifestSnapshot:manifest, provenance }; versions.set(key,row); return row; },
    async resolveModuleVersion({ moduleId, semanticVersion }){ return versions.get(`${moduleId}|${semanticVersion}`)||null; },
    async getOrganizationModule({ logtoOrganizationId, moduleId }){ return orgModules.get(`${logtoOrganizationId}|${moduleId}`)||null; },
    async listOrganizationModules({ logtoOrganizationId }){ return [...orgModules.values()].filter(r=>r.logtoOrganizationId===logtoOrganizationId); },
    async insertOrganizationModule(input){ const actor=normalizeActor(input); const row={ id:id('om'), logtoOrganizationId:input.logtoOrganizationId, moduleId:input.moduleId, moduleVersionId:input.moduleVersionId, lifecycle:input.lifecycle||'disabled', version:1, ...actor, operationalProvenance:input.operationalProvenance||{} }; orgModules.set(`${row.logtoOrganizationId}|${row.moduleId}`,row); audit.push({ action:'module.installation.provisioned', row }); outbox.push({ type:'module.installation.changed', organizationId:row.logtoOrganizationId, moduleId:row.moduleId }); return row; },
    async updateOrganizationModuleLifecycle({ logtoOrganizationId, moduleId, expectedVersion, lifecycle, actorLogtoUserId, reason, correlationId }){ const row=orgModules.get(`${logtoOrganizationId}|${moduleId}`); if(!row || row.version!==expectedVersion) throw new ModuleControlPlaneError(REASON_CODES.CONFLICT,'stale organization module version',{ logtoOrganizationId,moduleId,expectedVersion }); Object.assign(row,{ lifecycle, version:row.version+1, actorLogtoUserId, reason, correlationId:correlationId||null }); audit.push({ action:'module.lifecycle.transitioned', row }); outbox.push({ type:'module.lifecycle.changed', organizationId:logtoOrganizationId, moduleId, lifecycle }); return row; },
    async upsertRuntime(input){ assertNoSecrets({ metadata:input.compatibilityMetadata, healthPolicy:input.healthPolicy, serviceRef:input.serviceRef }); if(input.secretsRef) assertNoSecrets({ secretsRef:input.secretsRef }); const row={ id:input.id||id('rt'), runtimeId:input.runtimeId, moduleId:input.moduleId, moduleOwner:input.moduleOwner, deploymentMode:input.deploymentMode, serviceRef:input.serviceRef||null, runtimeContractVersion:input.runtimeContractVersion, expectedAudience:input.expectedAudience||null, serviceIdentityRequired:!!input.serviceIdentityRequired, healthPolicy:input.healthPolicy||{}, secretsRef:input.secretsRef||null, compatibilityMetadata:input.compatibilityMetadata||{}, runtimeStatus:input.runtimeStatus||'planned', version:1, provenance:input.provenance||{} }; runtimes.set(row.runtimeId,row); audit.push({ action:'module.runtime.registered', row:redactedRuntime(row) }); outbox.push({ type:'module.runtime.changed', moduleId:row.moduleId, runtimeId:row.runtimeId }); return row; },
    async getRuntimeByRuntimeId(runtimeId){ return runtimes.get(runtimeId)||null; },
    async getRuntimeByDatabaseId(databaseId){ return [...runtimes.values()].find((r)=>r.id===databaseId)||null; },
    async recordCompatibility(input){ const row={ id:id('cmp'), ...input }; compat.set(`${input.moduleVersionId}|${input.runtimeId}`,row); audit.push({ action:'module.compatibility.recorded', row }); outbox.push({ type:'module.compatibility.changed', moduleVersionId:input.moduleVersionId }); return row; },
    async getCompatibility({ moduleVersionId, runtimeId }){ return compat.get(`${moduleVersionId}|${runtimeId}`)||null; },
    async insertBinding(input){ const actor=normalizeActor(input); assertNoSecrets(input.operationalConfig||{}, 'operationalConfig'); const key=`${input.logtoOrganizationId}|${input.organizationModuleId}|${input.moduleId}`; if(input.isExecutable && [...bindings.values()].some(b=>b.logtoOrganizationId===input.logtoOrganizationId && b.organizationModuleId===input.organizationModuleId && b.moduleId===input.moduleId && b.isExecutable && b.status==='bound')) throw new ModuleControlPlaneError(REASON_CODES.DUPLICATE_BINDING,'duplicate active module runtime binding',{ key }); const row={ id:id('bind'), version:1, status:'planned', isExecutable:false, ...input, ...actor }; bindings.set(row.id,row); audit.push({ action:'module.runtime.binding.changed', row }); outbox.push({ type:'module.runtime.binding.changed', organizationId:row.logtoOrganizationId, moduleId:row.moduleId }); return row; },
    async listBindings({ logtoOrganizationId, moduleId }){ return [...bindings.values()].filter(b=>b.logtoOrganizationId===logtoOrganizationId && (!moduleId || b.moduleId===moduleId)); },
    async updateBindingStatus({ logtoOrganizationId, bindingId, expectedVersion, status='suspended', actorLogtoUserId, reason, correlationId }){ const row=[...bindings.values()].find(b=>b.id===bindingId && b.logtoOrganizationId===logtoOrganizationId); if(!row || row.version!==expectedVersion) throw new ModuleControlPlaneError(REASON_CODES.BINDING_CONFLICT,'stale runtime binding version',{ bindingId }); Object.assign(row,{ status, isExecutable:false, version:row.version+1, actorLogtoUserId, reason, correlationId:correlationId||null }); audit.push({ action:'module.runtime.binding.changed', row }); outbox.push({ type:'module.runtime.binding.changed', organizationId:row.logtoOrganizationId, moduleId:row.moduleId }); return row; }
  };
}

function createPostgresModuleControlPlaneRepository({ db, pool, clock=()=>new Date(), auditWriter=writeAudit, outboxWriter=writeOutbox }={}){
  const { getDb, getPool, schema } = require('../lib/db');
  const { and, desc, eq, sql } = require('drizzle-orm');
  if(!db) db = getDb();
  if(!pool) pool = getPool();
  const t=schema;
  async function transaction(work){ return db.transaction(async (tx)=>work(tx)); }
  async function emit(tx, { action, row, eventType, actorLogtoUserId, reason }){
    const safeRow = row?.secretsRef ? redactedRuntime(row) : row;
    await auditWriter(tx,{ action, logtoOrganizationId: row?.logtoOrganizationId || null, actorLogtoUserId: actorLogtoUserId || row?.actorLogtoUserId || null, targetId: row?.id || row?.runtimeId || row?.moduleId || null, metadata:{ row:safeRow, reason } });
    await outboxWriter(tx,{ type:eventType || action, logtoOrganizationId: row?.logtoOrganizationId || null, entityId: row?.id || row?.runtimeId || row?.moduleId || null, payload:{ moduleId:row?.moduleId, status:row?.status, lifecycle:row?.lifecycle, version:row?.version } });
  }
  async function one(rows){ return rows[0] || null; }
  return {
    kind:'postgres', pool,
    async upsertCatalogFromManifest(manifest, provenance={}){ const values={ moduleId:manifest.id, kind:manifest.kind, businessOwner:manifest.ownership.businessOwner, catalogStatus:manifest.status, catalogVersion:'2.0.0', catalogHash:loadCatalogHash(), provenance, updatedAt:new Date() }; const rows=await db.insert(t.moduleCatalog).values(values).onConflictDoUpdate({ target:t.moduleCatalog.moduleId, set:{ kind:values.kind, businessOwner:values.businessOwner, catalogStatus:values.catalogStatus, catalogVersion:values.catalogVersion, catalogHash:values.catalogHash, provenance:values.provenance, updatedAt:values.updatedAt } }).returning(); return one(rows); },
    async publishModuleVersion(manifest, provenance={}){ const values={ moduleId:manifest.id, semanticVersion:manifest.version, manifestSchemaVersion:manifest.schemaVersion, manifestHash:hashManifest(manifest), deploymentMode:manifest.deploymentMode, contractStatus:manifest.status, dataOwnership:manifest.dataOwnership, contractRefs:{ contributions:manifest.contributions, federated:manifest.federated||null }, compatibilityPolicy:manifest.compatibility.policy, manifestSnapshot:manifest, provenance }; const inserted=await db.insert(t.moduleVersions).values(values).onConflictDoNothing().returning(); if(inserted[0]) return inserted[0]; return this.resolveModuleVersion({ moduleId:manifest.id, semanticVersion:manifest.version }); },
    async resolveModuleVersion({ moduleId, semanticVersion }){ return one(await db.select().from(t.moduleVersions).where(and(eq(t.moduleVersions.moduleId,moduleId), eq(t.moduleVersions.semanticVersion,semanticVersion))).limit(1)); },
    async getOrganizationModule({ logtoOrganizationId, moduleId }){ return one(await db.select().from(t.organizationModules).where(and(eq(t.organizationModules.logtoOrganizationId,logtoOrganizationId), eq(t.organizationModules.moduleId,moduleId))).limit(1)); },
    async listOrganizationModules({ logtoOrganizationId }){ return db.select().from(t.organizationModules).where(eq(t.organizationModules.logtoOrganizationId,logtoOrganizationId)); },
    async insertOrganizationModule(input){ const actor=normalizeActor(input); return transaction(async(tx)=>{ const rows=await tx.insert(t.organizationModules).values({ logtoOrganizationId:input.logtoOrganizationId, moduleId:input.moduleId, moduleVersionId:input.moduleVersionId, lifecycle:input.lifecycle||'disabled', actorLogtoUserId:actor.actorLogtoUserId, reason:actor.reason, correlationId:actor.correlationId, operationalProvenance:input.operationalProvenance||{}, installedAt:new Date() }).onConflictDoNothing().returning(); const row=rows[0] || await one(await tx.select().from(t.organizationModules).where(and(eq(t.organizationModules.logtoOrganizationId,input.logtoOrganizationId), eq(t.organizationModules.moduleId,input.moduleId))).limit(1)); if(rows[0]){ await emit(tx,{ action:'module.installation.provisioned', eventType:'module.installation.changed', row, actorLogtoUserId:actor.actorLogtoUserId, reason:actor.reason }); } return row; }); },
    async updateOrganizationModuleLifecycle({ logtoOrganizationId, moduleId, expectedVersion, lifecycle, actorLogtoUserId, reason, correlationId }){ return transaction(async(tx)=>{ const rows=await tx.update(t.organizationModules).set({ lifecycle, version:sql`${t.organizationModules.version} + 1`, actorLogtoUserId, reason, correlationId:correlationId||null, lifecycleUpdatedAt:new Date(), updatedAt:new Date() }).where(and(eq(t.organizationModules.logtoOrganizationId,logtoOrganizationId), eq(t.organizationModules.moduleId,moduleId), eq(t.organizationModules.version,expectedVersion))).returning(); if(!rows[0]) throw new ModuleControlPlaneError(REASON_CODES.CONFLICT,'stale organization module version',{ logtoOrganizationId,moduleId,expectedVersion }); await emit(tx,{ action:'module.lifecycle.transitioned', eventType:'module.lifecycle.changed', row:rows[0], actorLogtoUserId, reason }); return rows[0]; }); },
    async upsertRuntime(input){ assertNoSecrets({ metadata:input.compatibilityMetadata, healthPolicy:input.healthPolicy, serviceRef:input.serviceRef }); if(input.secretsRef) assertNoSecrets({ secretsRef:input.secretsRef }); return transaction(async(tx)=>{ const values={ runtimeId:input.runtimeId, moduleId:input.moduleId, moduleOwner:input.moduleOwner, deploymentMode:input.deploymentMode, serviceRef:input.serviceRef||null, runtimeContractVersion:input.runtimeContractVersion, expectedAudience:input.expectedAudience||null, serviceIdentityRequired:!!input.serviceIdentityRequired, healthPolicy:input.healthPolicy||{}, secretsRef:input.secretsRef||null, compatibilityMetadata:input.compatibilityMetadata||{}, runtimeStatus:input.runtimeStatus||'planned', provenance:input.provenance||{}, updatedAt:new Date() }; const rows=await tx.insert(t.moduleRuntimeCatalog).values(values).onConflictDoUpdate({ target:t.moduleRuntimeCatalog.runtimeId, set:{ moduleOwner:values.moduleOwner, deploymentMode:values.deploymentMode, serviceRef:values.serviceRef, runtimeContractVersion:values.runtimeContractVersion, expectedAudience:values.expectedAudience, serviceIdentityRequired:values.serviceIdentityRequired, healthPolicy:values.healthPolicy, secretsRef:values.secretsRef, compatibilityMetadata:values.compatibilityMetadata, runtimeStatus:values.runtimeStatus, provenance:values.provenance, version:sql`${t.moduleRuntimeCatalog.version} + 1`, updatedAt:values.updatedAt } }).returning(); await emit(tx,{ action:'module.runtime.registered', eventType:'module.runtime.changed', row:rows[0] }); return rows[0]; }); },
    async getRuntimeByRuntimeId(runtimeId){ return one(await db.select().from(t.moduleRuntimeCatalog).where(eq(t.moduleRuntimeCatalog.runtimeId,runtimeId)).limit(1)); },
    async getRuntimeByDatabaseId(databaseId){ return one(await db.select().from(t.moduleRuntimeCatalog).where(eq(t.moduleRuntimeCatalog.id,databaseId)).limit(1)); },
    async recordCompatibility(input){ return transaction(async(tx)=>{ try { const rows=await tx.insert(t.moduleContractCompatibility).values({ moduleVersionId:input.moduleVersionId, runtimeId:input.runtimeDatabaseId||input.runtimeId, hostContractVersion:input.hostContractVersion, runtimeContractVersion:input.runtimeContractVersion, uiContractVersion:input.uiContractVersion||null, compatibilityStatus:input.compatibilityStatus, compatibilityRange:input.compatibilityRange, policy:input.policy, evidence:input.evidence||{}, provenance:input.provenance||{} }).returning(); await emit(tx,{ action:'module.compatibility.recorded', eventType:'module.compatibility.changed', row:rows[0] }); return rows[0]; } catch(error){ if(isUniqueViolation(error) && (error.constraint === 'module_contract_compatibility_identity_uidx' || !error.constraint)) throw new ModuleControlPlaneError('MODULE_CONTRACT_COMPATIBILITY_DUPLICATE','duplicate module/runtime compatibility record',{ moduleVersionId:input.moduleVersionId, runtimeId:input.runtimeId }); throw error; } }); },
    async getCompatibility({ moduleVersionId, runtimeId }){ return one(await db.select().from(t.moduleContractCompatibility).where(and(eq(t.moduleContractCompatibility.moduleVersionId,moduleVersionId), eq(t.moduleContractCompatibility.runtimeId,runtimeId))).orderBy(desc(t.moduleContractCompatibility.createdAt)).limit(1)); },
    async insertBinding(input){ const actor=normalizeActor(input); assertNoSecrets(input.operationalConfig||{}, 'operationalConfig'); return transaction(async(tx)=>{ const installation=await one(await tx.select().from(t.organizationModules).where(and(eq(t.organizationModules.id,input.organizationModuleId), eq(t.organizationModules.logtoOrganizationId,input.logtoOrganizationId), eq(t.organizationModules.moduleId,input.moduleId))).limit(1)); if(!installation) throw new ModuleControlPlaneError(REASON_CODES.WRONG_TENANT,'module installation is not visible for tenant binding',{ moduleId:input.moduleId }); try { const rows=await tx.insert(t.organizationModuleRuntimeBindings).values({ logtoOrganizationId:input.logtoOrganizationId, organizationModuleId:input.organizationModuleId, runtimeId:input.runtimeId, moduleId:input.moduleId, selectedContractVersion:input.selectedContractVersion, expectedContractVersion:input.expectedContractVersion, status:input.status||'planned', isExecutable:!!input.isExecutable, actorLogtoUserId:actor.actorLogtoUserId, reason:actor.reason, correlationId:actor.correlationId, operationalConfig:input.operationalConfig||{}, provenance:input.provenance||{} }).returning(); await emit(tx,{ action:'module.runtime.binding.changed', eventType:'module.runtime.binding.changed', row:rows[0], actorLogtoUserId:actor.actorLogtoUserId, reason:actor.reason }); return rows[0]; } catch(error){ if(isUniqueViolation(error)) throw new ModuleControlPlaneError(REASON_CODES.DUPLICATE_BINDING,'duplicate active module runtime binding',{ moduleId:input.moduleId }); throw error; } }); },
    async listBindings({ logtoOrganizationId, moduleId }){ const conditions=[eq(t.organizationModuleRuntimeBindings.logtoOrganizationId,logtoOrganizationId)]; if(moduleId) conditions.push(eq(t.organizationModuleRuntimeBindings.moduleId,moduleId)); return db.select().from(t.organizationModuleRuntimeBindings).where(and(...conditions)); },
    async updateBindingStatus({ logtoOrganizationId, bindingId, expectedVersion, status='suspended', actorLogtoUserId, reason, correlationId }){ return transaction(async(tx)=>{ const rows=await tx.update(t.organizationModuleRuntimeBindings).set({ status, isExecutable:false, version:sql`${t.organizationModuleRuntimeBindings.version} + 1`, actorLogtoUserId, reason, correlationId:correlationId||null, updatedAt:new Date() }).where(and(eq(t.organizationModuleRuntimeBindings.logtoOrganizationId,logtoOrganizationId), eq(t.organizationModuleRuntimeBindings.id,bindingId), eq(t.organizationModuleRuntimeBindings.version,expectedVersion))).returning(); if(!rows[0]) throw new ModuleControlPlaneError(REASON_CODES.BINDING_CONFLICT,'stale runtime binding version',{ bindingId }); await emit(tx,{ action:'module.runtime.binding.changed', eventType:'module.runtime.binding.changed', row:rows[0], actorLogtoUserId, reason }); return rows[0]; }); }
  };
}

function createModuleControlPlaneService({ repository, hooks={} }={}){
  if(!repository) throw new ModuleControlPlaneError(REASON_CODES.REPOSITORY_REQUIRED,'Module control plane repository is required; production must use PostgreSQL and tests must inject an explicit test double.');
  async function emitTransactional(action, payload){ if(hooks.audit) await hooks.audit({ action, payload }); if(hooks.outbox) await hooks.outbox({ type:action, payload }); }
  return {
    repository,
    async seedCatalogFromP3_002(){ const c=loadAuthoredCatalog(); const rows=[]; for(const m of c.modules){ rows.push({ catalog:await repository.upsertCatalogFromManifest(m,{ source:'contracts/modules/module-catalog.v2.json' }), version:await repository.publishModuleVersion(m,{ source:'contracts/modules/module-catalog.v2.json' }) }); } return rows; },
    async resolveModuleVersion(input){ return repository.resolveModuleVersion(input); },
    async getOrganizationModule(input){ return repository.getOrganizationModule(input); },
    async provisionOrganizationModule(input){ normalizeActor(input); const existing=await repository.getOrganizationModule(input); if(existing) return existing; const row=await repository.insertOrganizationModule({ lifecycle:'disabled', ...input }); await emitTransactional('module.installation.provisioned',{ organizationId:row.logtoOrganizationId, moduleId:row.moduleId }); return row; },
    async registerModuleRuntime(input){ required(input.runtimeId,'runtimeId'); required(input.moduleId,'moduleId'); required(input.runtimeContractVersion,'runtimeContractVersion'); const row=await repository.upsertRuntime(input); await emitTransactional('module.runtime.registered',{ moduleId:row.moduleId, runtimeId:row.runtimeId }); return row; },
    async updateModuleRuntime(input){ return this.registerModuleRuntime(input); },
    async recordModuleRuntimeCompatibility(input){ return repository.recordCompatibility(input); },
    async evaluateModuleRuntimeCompatibility({ moduleVersionId, runtimeId }){ const row=await repository.getCompatibility({ moduleVersionId, runtimeId }); if(!row || !COMPATIBLE.has(row.compatibilityStatus)) return { compatible:false, reasonCode:REASON_CODES.INCOMPATIBLE, compatibilityStatus:row?.compatibilityStatus||'verification_required', compatibilityVersion:row?.id||null }; return { compatible:true, compatibilityStatus:row.compatibilityStatus, compatibilityVersion:row.id }; },
    async bindOrganizationModuleRuntime(input){ const installation=await repository.getOrganizationModule({ logtoOrganizationId:input.logtoOrganizationId, moduleId:input.moduleId }); if(!installation) throw new ModuleControlPlaneError(REASON_CODES.NOT_EXECUTABLE,'module installation is required',{ moduleId:input.moduleId }); const runtime=await repository.getRuntimeByRuntimeId(input.runtimeId); if(!runtime) throw new ModuleControlPlaneError(REASON_CODES.UNAVAILABLE,'runtime is unavailable',{ runtimeId:input.runtimeId }); if(runtime.moduleId!==input.moduleId) throw new ModuleControlPlaneError(REASON_CODES.WRONG_MODULE,'runtime belongs to another module',{ runtimeId:input.runtimeId }); if(runtime.runtimeStatus !== 'available') throw new ModuleControlPlaneError(REASON_CODES.UNAVAILABLE,'runtime is not available for executable binding',{ runtimeId:input.runtimeId, runtimeStatus:runtime.runtimeStatus }); const compatibility=await this.evaluateModuleRuntimeCompatibility({ moduleVersionId:installation.moduleVersionId, runtimeId:runtime.id }); if(!compatibility.compatible) throw new ModuleControlPlaneError(REASON_CODES.INCOMPATIBLE,'runtime compatibility is not executable',{ status:compatibility.compatibilityStatus }); return repository.insertBinding({ organizationModuleId:installation.id, selectedContractVersion:runtime.runtimeContractVersion, expectedContractVersion:runtime.runtimeContractVersion, status:'bound', isExecutable:true, ...input, runtimeId:runtime.id }); },
    async suspendOrRemoveRuntimeBinding(input){ normalizeActor(input); return repository.updateBindingStatus({ ...input, status:input.status||'suspended' }); },
    async transitionOrganizationModuleLifecycle(input){ const actor=normalizeActor(input); const current=await repository.getOrganizationModule(input); if(!current) throw new ModuleControlPlaneError(REASON_CODES.NOT_EXECUTABLE,'module installation not found',{ moduleId:input.moduleId }); if(!lifecycleAllowed(current.lifecycle,input.toLifecycle)) throw new ModuleControlPlaneError(REASON_CODES.INVALID, 'invalid module lifecycle transition', { from:current.lifecycle, to:input.toLifecycle }); if(input.toLifecycle==='active'){ const bindings=await repository.listBindings({ logtoOrganizationId:input.logtoOrganizationId, moduleId:input.moduleId }); if(!bindings.some(b=>b.isExecutable && EXECUTABLE_BINDING.has(b.status))) throw new ModuleControlPlaneError(REASON_CODES.MISSING_BINDING,'active lifecycle requires executable runtime binding',{ moduleId:input.moduleId }); } const row=await repository.updateOrganizationModuleLifecycle({ ...input, lifecycle:input.toLifecycle, ...actor }); await emitTransactional('module.lifecycle.transitioned',{ organizationId:row.logtoOrganizationId, moduleId:row.moduleId, lifecycle:row.lifecycle }); return row; },
    async resolveModuleAvailability(input){ const om=await repository.getOrganizationModule(input); if(!om || ['disabled','suspended','decommissioning'].includes(om.lifecycle)) return { available:false, reasonCode:REASON_CODES.NOT_EXECUTABLE, lifecycle:om?.lifecycle||'missing' }; if(['active','degraded'].includes(om.lifecycle)){ const bindings=await repository.listBindings({ logtoOrganizationId:input.logtoOrganizationId, moduleId:input.moduleId }); const binding=bindings.find(b=>b.isExecutable && b.status==='bound'); if(!binding) return { available:false, reasonCode:REASON_CODES.MISSING_BINDING, lifecycle:om.lifecycle }; } return { available:om.lifecycle==='active' || om.lifecycle==='degraded', lifecycle:om.lifecycle }; }
  };
}
function createProductionModuleControlPlaneService(options={}){ return createModuleControlPlaneService({ ...options, repository: createPostgresModuleControlPlaneRepository(options) }); }

module.exports = { LIFECYCLES, TRANSITIONS, REASON_CODES, ModuleControlPlaneError, assertNoSecrets, createInMemoryModuleControlPlaneRepository, createPostgresModuleControlPlaneRepository, createModuleControlPlaneService, createProductionModuleControlPlaneService, hashManifest, loadAuthoredCatalog, loadCatalogHash };
