const { randomUUID } = require('node:crypto');
const { loadAuthoredCatalog, loadCatalogHash } = require('./moduleControlPlane');

const RESOLVER_VERSION = 'civitas-module-availability-resolver/v1';
const DECISION_SCHEMA_VERSION = 'civitas-module-availability-decision/v1';
const HEALTH_TARGETS = Object.freeze({ MODULE_RUNTIME_BINDING: 'module_runtime_binding', CAPABILITY_ADAPTER_BINDING: 'capability_adapter_binding' });
const EXECUTION_KINDS = new Set(['read','write','asynchronous','stream','administrative']);

const PROVENANCE_ALLOWED_KEYS = new Set(['source','checkId','observedBy','resolverVersion','catalogHash','moduleManifestHash','reasonCode']);
function normalizeProvenanceKey(key){ return String(key).replace(/[^a-z0-9]/gi,'').toLowerCase(); }
function isPrivateHostname(hostname){
  const h=String(hostname||'').toLowerCase();
  return h === 'localhost' || h.endsWith('.local') || h.startsWith('10.') || h.startsWith('127.') || h.startsWith('169.254.') || h.startsWith('192.168.') || /^172\.(1[6-9]|2[0-9]|3[0-1])\./.test(h) || h === '::1' || h.startsWith('fc') || h.startsWith('fd');
}
function assertSafeAvailabilityProvenance(value, path='provenance'){
  if(value == null) return {};
  if(!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${path} must be an object`);
  const out = {};
  for (const [key, raw] of Object.entries(value)) {
    const normalized = normalizeProvenanceKey(key);
    if(!PROVENANCE_ALLOWED_KEYS.has(key) || /token|secret|password|authorization|bearer|cookie|headers|request|response|body|providerpayload|payload/.test(normalized)) throw new Error(`${path}.${key} is not allowed`);
    if(typeof raw !== 'string' || raw.length === 0 || raw.length > 256) throw new Error(`${path}.${key} must be a non-empty string`);
    if(/stack\s*trace|^\s*at\s+\S+|\n\s*at\s+\S+/i.test(raw)) throw new Error(`${path}.${key} contains unsafe diagnostic provenance`);
    if(/^[a-z][a-z0-9+.-]*:\/\/[^/\s]+:[^/\s]+@/i.test(raw)) throw new Error(`${path}.${key} contains credentials`);
    if(/^[a-z][a-z0-9+.-]*:\/\//i.test(raw)) {
      let url;
      try { url = new URL(raw); } catch (_error) { throw new Error(`${path}.${key} must not contain raw URLs`); }
      if(url.username || url.password || isPrivateHostname(url.hostname)) throw new Error(`${path}.${key} contains unsafe URL provenance`);
    }
    out[key] = raw;
  }
  return Object.freeze(out);
}

const REASON_CODES = Object.freeze({
  AVAILABLE: 'module_available',
  OPERATION_UNKNOWN: 'operation_unknown',
  OPERATION_CONTRACT_MISMATCH: 'operation_contract_mismatch',
  MODULE_UNKNOWN: 'module_unknown',
  MODULE_NOT_INSTALLED: 'module_not_installed',
  MODULE_DISABLED: 'module_disabled',
  MODULE_PROVISIONING: 'module_provisioning',
  MODULE_SUSPENDED: 'module_suspended',
  MODULE_DECOMMISSIONING: 'module_decommissioning',
  MODULE_LIFECYCLE_UNKNOWN: 'module_lifecycle_unknown',
  CAPABILITY_NOT_DECLARED: 'capability_not_declared',
  RUNTIME_BINDING_MISSING: 'runtime_binding_missing',
  RUNTIME_BINDING_INACTIVE: 'runtime_binding_inactive',
  RUNTIME_INCOMPATIBLE: 'runtime_incompatible',
  HEALTH_SNAPSHOT_MISSING: 'health_snapshot_missing',
  HEALTH_SNAPSHOT_STALE: 'health_snapshot_stale',
  HEALTH_SNAPSHOT_UNKNOWN: 'health_snapshot_unknown',
  RUNTIME_UNAVAILABLE: 'runtime_unavailable',
  RUNTIME_CIRCUIT_OPEN: 'runtime_circuit_open',
  RUNTIME_CIRCUIT_HALF_OPEN: 'runtime_circuit_half_open',
  DEGRADED_POLICY_MISSING: 'degraded_policy_missing',
  MODULE_DEGRADED_READ_ONLY: 'module_degraded_read_only',
  MODULE_DEGRADED_OPERATION_DENIED: 'module_degraded_operation_denied'
});
function isoNow(clock){ const d = clock ? clock() : new Date(); return d instanceof Date ? d.toISOString() : new Date(d).toISOString(); }
function moduleManifest(moduleId){ return loadAuthoredCatalog().modules.find((m)=>m.id===moduleId) || null; }
function capabilitiesFor(manifest){ return new Set((manifest?.capabilities||[]).map((c)=>typeof c === 'string' ? c : c.id)); }
function stableDecisionId(input){ return `mav_${Buffer.from(`${input.organizationId}|${input.moduleId}|${input.capabilityId}|${input.operationId}|${input.evaluatedAt||''}`).toString('base64url').slice(0,32)}_${randomUUID().slice(0,8)}`; }
function publicAvailabilityReadModel(decision){ return Object.freeze({ moduleId: decision.moduleId, capabilityId: decision.capabilityId, state: decision.state, executable: decision.executable, readOnly: decision.readOnly, partialCapabilities: decision.partialCapabilities, reasonCode: decision.reasonCode, observedAt: decision.observedAt, expiresAt: decision.expiresAt, versionToken: decision.decisionId }); }
function createStaticOperationRegistry(operations=[]){ const byId=new Map(operations.map((op)=>[op.operationId,Object.freeze({ requiresBusinessRuntimeBinding:true, requiresHealth:true, requiresCompatibility:true, requiresCapabilityAdapterBinding:false, degradedPolicyId:null, ...op })])); return { getOperation(operationId){ return byId.get(operationId)||null; }, listOperations(){ return [...byId.values()]; } }; }
function createStaticDegradedPolicyRegistry(policies=[]){ const byKey=new Map(); for(const p of policies) byKey.set(`${p.moduleId}|${p.capabilityId||'*'}`, Object.freeze(p)); return { getPolicy({ moduleId, capabilityId }){ return byKey.get(`${moduleId}|${capabilityId}`)||byKey.get(`${moduleId}|*`)||null; } }; }
function createInMemoryAvailabilityStateRepository(){ const snapshots=[]; const circuits=new Map(); return { snapshots, circuits, async recordHealthSnapshot(s){ const row={ id:s.id||randomUUID(), version:s.version||snapshots.length+1, createdAt:isoNow(), ...s, provenance:assertSafeAvailabilityProvenance(s.provenance) }; snapshots.push(row); return row; }, async getLatestHealthSnapshot(q){ return snapshots.filter((s)=>s.logtoOrganizationId===q.organizationId && s.moduleId===q.moduleId && (!q.capabilityId || s.capabilityId===q.capabilityId) && (!q.targetBindingId || s.targetBindingId===q.targetBindingId)).sort((a,b)=>String(b.observedAt).localeCompare(String(a.observedAt)) || b.version-a.version)[0]||null; }, async writeCircuitState(s){ const key=`${s.organizationId}|${s.targetType}|${s.targetBindingId}`; const row={ version:(circuits.get(key)?.version||0)+1, updatedAt:isoNow(), ...s, provenance:assertSafeAvailabilityProvenance(s.provenance) }; circuits.set(key,row); return row; }, async readCircuitState(q){ return circuits.get(`${q.organizationId}|${q.targetType}|${q.targetBindingId}`)||null; } }; }
function createPostgresAvailabilityStateRepository({ pool }){ if(!pool) throw new Error('pool is required'); return { async recordHealthSnapshot(s){ const r=await pool.query(`insert into module_health_snapshots(logto_organization_id,target_type,target_binding_id,module_id,capability_id,observed_state,observed_at,expires_at,sanitized_reason,provenance) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`, [s.organizationId||s.logtoOrganizationId,s.targetType,s.targetBindingId,s.moduleId,s.capabilityId||null,s.observedState,s.observedAt,s.expiresAt,s.sanitizedReason||null,assertSafeAvailabilityProvenance(s.provenance)]); return r.rows[0]; }, async getLatestHealthSnapshot(q){ const r=await pool.query(`select * from module_health_snapshots where logto_organization_id=$1 and module_id=$2 and ($3::text is null or capability_id=$3) and ($4::uuid is null or target_binding_id=$4::uuid) order by observed_at desc, version desc limit 1`, [q.organizationId,q.moduleId,q.capabilityId||null,q.targetBindingId||null]); const row=r.rows[0]; return row && { id:row.id, version:row.version, logtoOrganizationId:row.logto_organization_id, targetType:row.target_type, targetBindingId:row.target_binding_id, moduleId:row.module_id, capabilityId:row.capability_id, observedState:row.observed_state, observedAt:row.observed_at.toISOString(), expiresAt:row.expires_at.toISOString(), sanitizedReason:row.sanitized_reason, provenance:row.provenance }; }, async writeCircuitState(s){ const r=await pool.query(`insert into module_circuit_states(logto_organization_id,target_type,target_binding_id,module_id,capability_id,state,provenance) values($1,$2,$3,$4,$5,$6,$7) on conflict(logto_organization_id,target_type,target_binding_id) do update set state=excluded.state, version=module_circuit_states.version+1, updated_at=now(), provenance=excluded.provenance returning *`, [s.organizationId,s.targetType,s.targetBindingId,s.moduleId,s.capabilityId||null,s.state,assertSafeAvailabilityProvenance(s.provenance)]); const row=r.rows[0]; return { version:row.version, organizationId:row.logto_organization_id, targetType:row.target_type, targetBindingId:row.target_binding_id, moduleId:row.module_id, capabilityId:row.capability_id, state:row.state, updatedAt:row.updated_at.toISOString(), provenance:row.provenance }; }, async readCircuitState(q){ const r=await pool.query(`select * from module_circuit_states where logto_organization_id=$1 and target_type=$2 and target_binding_id=$3 limit 1`, [q.organizationId,q.targetType,q.targetBindingId]); const row=r.rows[0]; return row && { version:row.version, organizationId:row.logto_organization_id, targetType:row.target_type, targetBindingId:row.target_binding_id, moduleId:row.module_id, capabilityId:row.capability_id, state:row.state, updatedAt:row.updated_at.toISOString(), provenance:row.provenance }; } }; }
function createModuleAvailabilityResolver({ moduleControlPlaneService, operationRegistry, stateRepository, degradedPolicyRegistry=createStaticDegradedPolicyRegistry(), clock=()=>new Date(), decisionIdFactory=stableDecisionId }={}){
  if(!moduleControlPlaneService) throw new Error('moduleControlPlaneService is required'); if(!operationRegistry) throw new Error('operationRegistry is required'); if(!stateRepository) throw new Error('stateRepository is required');
  function decision(input, fields){ const manifest=moduleManifest(input.moduleId); return Object.freeze({ schemaVersion:DECISION_SCHEMA_VERSION, decisionId:decisionIdFactory({...input,evaluatedAt:input.evaluatedAt||isoNow(clock)}), organizationId:input.organizationId, moduleId:input.moduleId, capabilityId:input.capabilityId, operationId:input.operationId, executionKind:input.executionKind, state:'unavailable', executable:false, readOnly:false, allowedExecutionKinds:[], partialCapabilities:[], lifecycle:'unknown', deploymentMode:manifest?.deploymentMode||'embedded', moduleVersion:manifest?.version||'unknown', installationVersion:'missing', reasonCode:fields.reasonCode, provenance:{ catalogHash:loadCatalogHash(), moduleManifestHash:manifest?.manifestHash||'unknown', resolverVersion:RESOLVER_VERSION }, ...fields }); }
  return { async resolve(input){ const evaluatedAt=input.evaluatedAt||isoNow(clock); if(!input.organizationId||!input.moduleId||!input.capabilityId||!input.operationId||!EXECUTION_KINDS.has(input.executionKind)) return decision({...input,evaluatedAt}, { reasonCode: REASON_CODES.OPERATION_CONTRACT_MISMATCH, state:'unknown' }); const op=operationRegistry.getOperation(input.operationId); if(!op) return decision({...input,evaluatedAt}, { reasonCode:REASON_CODES.OPERATION_UNKNOWN, state:'unknown' }); if(op.moduleId!==input.moduleId||op.capabilityId!==input.capabilityId||op.executionKind!==input.executionKind) return decision({...input,evaluatedAt}, { reasonCode:REASON_CODES.OPERATION_CONTRACT_MISMATCH, state:'unknown' }); const manifest=moduleManifest(input.moduleId); if(!manifest) return decision({...input,evaluatedAt}, { reasonCode:REASON_CODES.MODULE_UNKNOWN, state:'unknown' }); if(!capabilitiesFor(manifest).has(input.capabilityId)) return decision({...input,evaluatedAt}, { reasonCode:REASON_CODES.CAPABILITY_NOT_DECLARED, state:'unknown' }); const installation=await moduleControlPlaneService.getOrganizationModule({ logtoOrganizationId:input.organizationId, moduleId:input.moduleId }); if(!installation) return decision({...input,evaluatedAt}, { reasonCode:REASON_CODES.MODULE_NOT_INSTALLED, lifecycle:'missing' }); const base={ lifecycle:installation.lifecycle, installationVersion:String(installation.version), deploymentMode:manifest.deploymentMode, moduleVersion:manifest.version };
      if(installation.lifecycle==='disabled') return decision({...input,evaluatedAt}, { ...base, reasonCode:REASON_CODES.MODULE_DISABLED });
      if(installation.lifecycle==='provisioning') return decision({...input,evaluatedAt}, { ...base, reasonCode:REASON_CODES.MODULE_PROVISIONING });
      if(installation.lifecycle==='suspended') return decision({...input,evaluatedAt}, { ...base, reasonCode:REASON_CODES.MODULE_SUSPENDED });
      if(installation.lifecycle==='decommissioning') return decision({...input,evaluatedAt}, { ...base, reasonCode:REASON_CODES.MODULE_DECOMMISSIONING });
      if(!['active','degraded'].includes(installation.lifecycle)) return decision({...input,evaluatedAt}, { ...base, reasonCode:REASON_CODES.MODULE_LIFECYCLE_UNKNOWN, state:'unknown' });
      const bindings = op.requiresBusinessRuntimeBinding===false ? [] : await moduleControlPlaneService.repository.listBindings({ logtoOrganizationId:input.organizationId, moduleId:input.moduleId });
      const binding = bindings.find((b)=>b.isExecutable && b.status==='bound');
      if(op.requiresBusinessRuntimeBinding!==false && !binding) return decision({...input,evaluatedAt}, { ...base, reasonCode:REASON_CODES.RUNTIME_BINDING_MISSING });
      const bindingFields = binding ? { bindingVersion:String(binding.version), runtimeContractVersion:binding.selectedContractVersion } : {};
      if(op.requiresCompatibility!==false && binding){ const moduleVersion=await moduleControlPlaneService.resolveModuleVersion({ moduleId:input.moduleId, semanticVersion:manifest.version }); if(moduleVersion){ const compat=await moduleControlPlaneService.evaluateModuleRuntimeCompatibility({ moduleVersionId:moduleVersion.id, runtimeId:binding.runtimeId }); if(!compat.compatible) return decision({...input,evaluatedAt}, { ...base, ...bindingFields, reasonCode:REASON_CODES.RUNTIME_INCOMPATIBLE }); } }
      if(op.requiresHealth!==false && binding){ const snap=await stateRepository.getLatestHealthSnapshot({ organizationId:input.organizationId, moduleId:input.moduleId, capabilityId:input.capabilityId, targetBindingId:binding.id }); if(!snap) return decision({...input,evaluatedAt}, { ...base, ...bindingFields, reasonCode:REASON_CODES.HEALTH_SNAPSHOT_MISSING, state:'unknown' }); if(new Date(snap.expiresAt).getTime() <= new Date(evaluatedAt).getTime()) return decision({...input,evaluatedAt}, { ...base, ...bindingFields, healthSnapshotVersion:String(snap.version), observedAt:snap.observedAt, expiresAt:snap.expiresAt, reasonCode:REASON_CODES.HEALTH_SNAPSHOT_STALE, state:'unknown' }); if(snap.observedState==='unavailable') return decision({...input,evaluatedAt}, { ...base, ...bindingFields, healthSnapshotVersion:String(snap.version), observedAt:snap.observedAt, expiresAt:snap.expiresAt, reasonCode:REASON_CODES.RUNTIME_UNAVAILABLE }); if(snap.observedState==='unknown') return decision({...input,evaluatedAt}, { ...base, ...bindingFields, healthSnapshotVersion:String(snap.version), observedAt:snap.observedAt, expiresAt:snap.expiresAt, reasonCode:REASON_CODES.HEALTH_SNAPSHOT_UNKNOWN, state:'unknown' }); if(snap.observedState==='degraded'){ const policy=degradedPolicyRegistry.getPolicy({ moduleId:input.moduleId, capabilityId:input.capabilityId }); if(!policy) return decision({...input,evaluatedAt}, { ...base, ...bindingFields, healthSnapshotVersion:String(snap.version), observedAt:snap.observedAt, expiresAt:snap.expiresAt, reasonCode:REASON_CODES.DEGRADED_POLICY_MISSING, state:'degraded' }); if(policy.mode==='unavailable') return decision({...input,evaluatedAt}, { ...base, ...bindingFields, healthSnapshotVersion:String(snap.version), observedAt:snap.observedAt, expiresAt:snap.expiresAt, reasonCode:REASON_CODES.MODULE_DEGRADED_OPERATION_DENIED, state:'degraded' }); if(policy.mode==='read_only' && input.executionKind!=='read') return decision({...input,evaluatedAt}, { ...base, ...bindingFields, healthSnapshotVersion:String(snap.version), observedAt:snap.observedAt, expiresAt:snap.expiresAt, reasonCode:REASON_CODES.MODULE_DEGRADED_READ_ONLY, state:'degraded', readOnly:true, allowedExecutionKinds:['read'] }); if(policy.mode==='read_only') return decision({...input,evaluatedAt}, { ...base, ...bindingFields, healthSnapshotVersion:String(snap.version), observedAt:snap.observedAt, expiresAt:snap.expiresAt, reasonCode:REASON_CODES.AVAILABLE, state:'degraded', executable:true, readOnly:true, allowedExecutionKinds:['read'] }); } }
      if(binding){ const circuit=await stateRepository.readCircuitState({ organizationId:input.organizationId, targetType:HEALTH_TARGETS.MODULE_RUNTIME_BINDING, targetBindingId:binding.id }); if(circuit?.state==='open') return decision({...input,evaluatedAt}, { ...base, ...bindingFields, circuitVersion:String(circuit.version), reasonCode:REASON_CODES.RUNTIME_CIRCUIT_OPEN }); if(circuit?.state==='half_open' && !op.isProbe) return decision({...input,evaluatedAt}, { ...base, ...bindingFields, circuitVersion:String(circuit.version), reasonCode:REASON_CODES.RUNTIME_CIRCUIT_HALF_OPEN, state:'degraded' }); }
      if(installation.lifecycle==='degraded'){ const policy=degradedPolicyRegistry.getPolicy({ moduleId:input.moduleId, capabilityId:input.capabilityId }); if(!policy) return decision({...input,evaluatedAt}, { ...base, ...bindingFields, reasonCode:REASON_CODES.DEGRADED_POLICY_MISSING, state:'degraded' }); if(policy.mode==='unavailable') return decision({...input,evaluatedAt}, { ...base, ...bindingFields, reasonCode:REASON_CODES.MODULE_DEGRADED_OPERATION_DENIED, state:'degraded' }); if(policy.mode==='read_only' && input.executionKind!=='read') return decision({...input,evaluatedAt}, { ...base, ...bindingFields, reasonCode:REASON_CODES.MODULE_DEGRADED_READ_ONLY, state:'degraded', readOnly:true, allowedExecutionKinds:['read'] }); }
      return decision({...input,evaluatedAt}, { ...base, ...bindingFields, state:installation.lifecycle==='degraded'?'degraded':'healthy', executable:true, readOnly:installation.lifecycle==='degraded', allowedExecutionKinds:installation.lifecycle==='degraded'?['read']:[input.executionKind], reasonCode:REASON_CODES.AVAILABLE }); } };
}
module.exports={ RESOLVER_VERSION, DECISION_SCHEMA_VERSION, REASON_CODES, HEALTH_TARGETS, createModuleAvailabilityResolver, createStaticOperationRegistry, createStaticDegradedPolicyRegistry, createInMemoryAvailabilityStateRepository, createPostgresAvailabilityStateRepository, publicAvailabilityReadModel, assertSafeAvailabilityProvenance, PROVENANCE_ALLOWED_KEYS };
