const test=require('node:test'); const assert=require('node:assert/strict'); const {Pool}=require('pg');
const {runSqlMigrations,assertOperationalSchema}=require('../runtime/migrations');
const {createPostgresIntegrationRepository,createIntegrationDispatcher,createIntegrationEvent,REASON_CODES,OPERATION_STATES,IntegrationEventError}=require('../services/integrationEvents');
if(!process.env.DATABASE_URL&&process.env.P3_010_POSTGRES_CHECK==='1') throw new Error('DATABASE_URL is required for integration:p3-010:postgres-check');
if(!process.env.DATABASE_URL){test('P3-010 PostgreSQL integration requires DATABASE_URL only in postgres-check',{skip:'DATABASE_URL is mandatory for integration:p3-010:postgres-check'},()=>{});return;}
async function reset(pool){await pool.query('drop schema if exists public cascade'); await pool.query('create schema public'); await pool.query('create extension if not exists pgcrypto');}
function e(id='00000000-0000-4000-8000-000000000001',org='orgA'){return createIntegrationEvent({eventId:id,eventType:'operations.operation.started',organizationId:org,aggregate:{type:'operation',id:'op1'},actor:{type:'system',serviceId:'svc'},correlation:{correlationId:`corr-${org}`},causation:{},source:{moduleId:'operations',capabilityId:'operations.lifecycle',component:'test'},payload:{operationId:'op1'}})}
test('PostgreSQL outbox/inbox operations support atomicity, duplicate delivery and tenant isolation',async()=>{const pool=new Pool({connectionString:process.env.DATABASE_URL,max:6});try{await reset(pool);await runSqlMigrations({pool,logger:{log(){}}});await assertOperationalSchema({pool});const repo=createPostgresIntegrationRepository({pool});await repo.appendEvent(e());await repo.appendEvent(e('00000000-0000-4000-8000-000000000002','orgB'));const [a,b]=await Promise.all([repo.claimBatch({limit:1,leaseOwner:'w1'}),repo.claimBatch({limit:1,leaseOwner:'w2'})]);assert.equal(new Set([a[0].event_id,b[0].event_id]).size,2);await repo.markPublished({eventId:a[0].event_id});assert.equal((await repo.findByEventId({organizationId:a[0].logto_organization_id,eventId:a[0].event_id})).state,'published');const receipt=await repo.claimInbox({consumerId:'operations.projection',event:e()});await repo.markInboxProcessed({consumerId:'operations.projection',eventId:e().eventId,result:{reference:'ok'}});await assert.rejects(()=>repo.claimInbox({consumerId:'operations.projection',event:e()}),{code:REASON_CODES.INBOX_DUPLICATE});assert.equal((await repo.findByEventId({organizationId:'orgB',eventId:e().eventId})),null);const op=await repo.createOperation({organizationId:'orgA',operationType:'integration.test',moduleId:'operations',capabilityId:'operations.lifecycle',requestedBy:{type:'system'},correlationId:'corr-op'});const queued=await repo.transitionOperation({organizationId:'orgA',operationId:op.id,expectedVersion:op.version,toState:OPERATION_STATES.QUEUED,principal:{principalType:'system'},reason:'queue'});const running=await repo.transitionOperation({organizationId:'orgA',operationId:op.id,expectedVersion:queued.version,toState:OPERATION_STATES.RUNNING,principal:{principalType:'system'},reason:'run',progress:{percentage:10}});await repo.transitionOperation({organizationId:'orgA',operationId:op.id,expectedVersion:running.version,toState:OPERATION_STATES.SUCCEEDED,principal:{principalType:'system'},reason:'done',result:{reference:'result'}});await assert.rejects(()=>repo.transitionOperation({organizationId:'orgA',operationId:op.id,expectedVersion:running.version,toState:OPERATION_STATES.RUNNING}),{code:REASON_CODES.OPERATION_VERSION_CONFLICT});await assert.rejects(()=>repo.transitionOperation({organizationId:'orgB',operationId:op.id,expectedVersion:1,toState:OPERATION_STATES.QUEUED}),{code:REASON_CODES.OPERATION_VERSION_CONFLICT});}finally{await pool.end();}});
test('dispatcher marks published after ack and sends terminal failures to DLQ',async()=>{const pool=new Pool({connectionString:process.env.DATABASE_URL,max:4});try{await reset(pool);await runSqlMigrations({pool,logger:{log(){}}});const repo=createPostgresIntegrationRepository({pool});await repo.appendEvent(e());const dispatcher=createIntegrationDispatcher({repository:repo,transport:{publish:async()=>true}});assert.equal((await dispatcher.dispatchOnce()).at(0).state,'published');await repo.appendEvent(e('00000000-0000-4000-8000-000000000003'));const bad=createIntegrationDispatcher({repository:repo,transport:{publish:async()=>{throw new IntegrationEventError(REASON_CODES.PAYLOAD_PROHIBITED,'bad')}}});const res=await bad.dispatchOnce();assert.equal(res[0].state,'terminal');const dlq=await pool.query('select * from integration_dead_letters');assert.equal(dlq.rowCount,1);}finally{await pool.end();}});
