import { resolveModuleUiArtifact, type HostApprovedArtifactRegistry } from "./artifactResolver.ts";
import { sha256Integrity, verifyIntegrity, verifySignature } from "./integrity.ts";
import { ModuleUiContributionCache } from "./cache.ts";
import { moduleUiFallbackState } from "./fallbackStates.ts";
import { compatibilityStatus, validateModuleUiContribution, type ModuleCatalogReadModel } from "./validator.ts";
import type { ModuleUiFailureCode, ModuleUiLoadResult, ModuleUiValidatedContribution } from "./contracts.ts";
export type SecureLoaderDeps = { catalog:ModuleCatalogReadModel; artifactRegistry:HostApprovedArtifactRegistry; cache?:ModuleUiContributionCache; publicKey?:CryptoKey; importVerifiedModule?:(content:string)=>Promise<Record<string, unknown>>; report?:(name:string, labels:Record<string,string>)=>void };
export async function loadSecureModuleUiContribution(input:unknown, deps:SecureLoaderDeps):Promise<ModuleUiLoadResult>{ let moduleId="unknown"; if(input && typeof input==="object" && !Array.isArray(input) && "identity" in input){ const identity=(input as { identity?:unknown }).identity; if(identity && typeof identity==="object" && !Array.isArray(identity) && "moduleId" in identity && typeof (identity as { moduleId?:unknown }).moduleId==="string") moduleId=(identity as { moduleId:string }).moduleId; } const correlationId=`mui_${moduleId}`; const fail=(code:ModuleUiFailureCode):ModuleUiLoadResult=>{ deps.report?.("module_ui_fallback",{ moduleId, outcome:"failure", failureCategory:code }); const f=moduleUiFallbackState(code, correlationId); return { ok:false, code, safeTitle:f.titleKey, safeDescription:f.descriptionKey, correlationId, fallbackState:code }; };
  const schema=validateModuleUiContribution(input,deps.catalog); if(!schema.ok) return fail(schema.code); const contribution=schema.contribution; moduleId=contribution.identity.moduleId; const compat=compatibilityStatus(contribution); if(!compat.ok) return fail(compat.code); const resolved=resolveModuleUiArtifact(contribution,deps.artifactRegistry); if(!resolved.ok) return fail(resolved.code); if(!await verifyIntegrity(resolved.artifact.content, contribution.artifact.integrity)) return fail("integrity_failure"); const graphPayload=JSON.stringify(contribution.artifact.assetManifest.assets.map(a=>[a.artifactId,a.integrity,a.contentType,a.sizeBytes])); if(await sha256Integrity(graphPayload)!==contribution.artifact.assetManifest.integrity) return fail("asset_graph_invalid"); if(!await verifySignature({ payload:graphPayload, signature:contribution.artifact.signature, publicKey:deps.publicKey })) return fail("signature_invalid"); const cache=deps.cache||new ModuleUiContributionCache(); const cacheKey=[contribution.identity.moduleId,contribution.identity.moduleVersion,contribution.contract.contributionVersion,contribution.contract.uiContractVersion,contribution.artifact.integrity,contribution.compatibility.designSystemVersion,contribution.compatibility.hostApiVersion].join("|"); const validated=Object.freeze({ ...contribution, validated:true as const, integrityVerified:true as const, compatibilityStatus:compat.status, resolvedArtifact:{ artifactId:resolved.artifact.artifactId, origin:resolved.artifact.origin, cacheKey } }) as ModuleUiValidatedContribution; const moduleExports=deps.importVerifiedModule ? await deps.importVerifiedModule(resolved.artifact.content).catch(()=>null) : { default:null }; if(!moduleExports){ const previous=cache.previous(contribution.identity.moduleId); const previousExports=cache.previousExports(contribution.identity.moduleId); if(previous && previousExports) return { ok:true, contribution:previous, moduleExports:previousExports, cacheState:"previous_verified" }; return fail("remote_error"); } cache.putVerified(validated,moduleExports); cache.activate(validated); deps.report?.("module_ui_loaded",{ moduleId:contribution.identity.moduleId, outcome:"success", failureCategory:"none" }); return { ok:true, contribution:validated, moduleExports, cacheState:"active" }; }
