import { resolveModuleUiArtifact, type HostApprovedArtifactRegistry } from "./artifactResolver.ts";
import { sha256Integrity, verifyIntegrity, verifySignature } from "./integrity.ts";
import { ModuleUiContributionCache } from "./cache.ts";
import { moduleUiFallbackState } from "./fallbackStates.ts";
import { compatibilityStatus, validateModuleUiContribution, type ModuleCatalogReadModel } from "./validator.ts";
import type { ModuleUiContribution, ModuleUiFailureCode, ModuleUiLoadResult, ModuleUiValidatedContribution } from "./contracts.ts";
export type SecureLoaderDeps = { catalog:ModuleCatalogReadModel; artifactRegistry:HostApprovedArtifactRegistry; cache?:ModuleUiContributionCache; publicKeyPem?:string; importVerifiedModule?:(content:string)=>Promise<Record<string, unknown>>; report?:(name:string, labels:Record<string,string>)=>void };
export async function loadSecureModuleUiContribution(contribution:ModuleUiContribution, deps:SecureLoaderDeps):Promise<ModuleUiLoadResult>{ const correlationId=`mui_${contribution?.identity?.moduleId || "unknown"}`; const fail=(code:ModuleUiFailureCode):ModuleUiLoadResult=>{ deps.report?.("module_ui_fallback",{ moduleId:contribution?.identity?.moduleId||"unknown", outcome:"failure", failureCategory:code }); const f=moduleUiFallbackState(code, correlationId); return { ok:false, code, safeTitle:f.titleKey, safeDescription:f.descriptionKey, correlationId, fallbackState:code }; };
  const schema=validateModuleUiContribution(contribution,deps.catalog); if(!schema.ok) return fail(schema.code); const compat=compatibilityStatus(contribution); if(!compat.ok) return fail(compat.code); const resolved=resolveModuleUiArtifact(contribution,deps.artifactRegistry); if(!resolved.ok) return fail(resolved.code); if(!verifyIntegrity(resolved.artifact.content, contribution.artifact.integrity)) return fail("integrity_failure"); const graphPayload=JSON.stringify(contribution.artifact.assetManifest.assets.map(a=>[a.artifactId,a.integrity,a.contentType,a.sizeBytes])); if(sha256Integrity(graphPayload)!==contribution.artifact.assetManifest.integrity) return fail("asset_graph_invalid"); if(!verifySignature({ payload:graphPayload, signature:contribution.artifact.signature, publicKeyPem:deps.publicKeyPem })) return fail("signature_invalid"); const cache=deps.cache||new ModuleUiContributionCache(); const cacheKey=[contribution.identity.moduleId,contribution.identity.moduleVersion,contribution.contract.contributionVersion,contribution.contract.uiContractVersion,contribution.artifact.integrity,contribution.compatibility.designSystemVersion,contribution.compatibility.hostApiVersion].join("|"); const validated=Object.freeze({ ...contribution, validated:true as const, integrityVerified:true as const, compatibilityStatus:compat.status, resolvedArtifact:{ artifactId:resolved.artifact.artifactId, origin:resolved.artifact.origin, cacheKey } }) as ModuleUiValidatedContribution; cache.putVerified(validated); const moduleExports=deps.importVerifiedModule ? await deps.importVerifiedModule(resolved.artifact.content).catch(()=>null) : { default:null }; if(!moduleExports){ const previous=cache.previous(contribution.identity.moduleId); if(previous) return { ok:true, contribution:previous, moduleExports:{ default:null }, cacheState:"previous_verified" }; return fail("remote_error"); } cache.activate(validated); deps.report?.("module_ui_loaded",{ moduleId:contribution.identity.moduleId, outcome:"success", failureCategory:"none" }); return { ok:true, contribution:validated, moduleExports, cacheState:"active" }; }
