import { MODULE_UI_CONTRACT_VERSION, MODULE_UI_HOST_API_VERSION, MODULE_UI_DESIGN_SYSTEM_VERSION, type ModuleUiContribution, type ModuleUiFailureCode } from "./contracts.ts";
export type ModuleCatalogReadModel = { modules:readonly { id:string; version:string; status:string; capabilities:readonly ({id:string}|string)[] }[]; catalogHash:string };
const idPattern=/^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)*$/;
export function validateModuleUiContribution(c:ModuleUiContribution, catalog:ModuleCatalogReadModel){ const fail=(code:ModuleUiFailureCode)=>({ ok:false as const, code });
  if(!c || c.contract?.schemaVersion!==MODULE_UI_CONTRACT_VERSION || c.contract.uiContractVersion!==MODULE_UI_CONTRACT_VERSION) return fail("schema_invalid"); if(c.compatibility.hostApiVersion!==MODULE_UI_HOST_API_VERSION) return fail("host_api_incompatible"); if(c.compatibility.designSystemVersion!==MODULE_UI_DESIGN_SYSTEM_VERSION) return fail("design_system_incompatible"); const mod=catalog.modules.find(m=>m.id===c.identity.moduleId); if(!mod) return fail("unknown_module"); const caps=new Set(mod.capabilities.map(x=>typeof x==="string"?x:x.id)); for(const x of [...c.routes,...c.screens,...c.actions]){ if(x.moduleId!==c.identity.moduleId) return fail("schema_invalid"); if(!caps.has(x.capabilityId)) return fail("unknown_capability"); }
  const routeIds=new Set<string>(), screenIds=new Set<string>(), actionIds=new Set<string>(); for(const r of c.routes){ if(routeIds.has(r.routeId) || !idPattern.test(r.routeId) || r.status!==c.contract.status) return fail("duplicate_id"); routeIds.add(r.routeId); if(!c.screens.some(s=>s.screenId===r.screenId)) return fail("schema_invalid"); }
  for(const s of c.screens){ if(screenIds.has(s.screenId) || !idPattern.test(s.screenId) || !routeIds.has(s.routeId) || s.status!==c.contract.status) return fail("duplicate_id"); screenIds.add(s.screenId); }
  for(const a of c.actions){ if(actionIds.has(a.actionId) || !idPattern.test(a.actionId) || !screenIds.has(a.screenId) || a.status!==c.contract.status) return fail("duplicate_id"); actionIds.add(a.actionId); }
  if(c.contract.status==="planned") return fail("planned_not_mountable"); return { ok:true as const };
}
export function compatibilityStatus(c:ModuleUiContribution){ if(c.compatibility.hostApiVersion!==MODULE_UI_HOST_API_VERSION) return { ok:false as const, code:"host_api_incompatible" as const }; if(c.compatibility.designSystemVersion!==MODULE_UI_DESIGN_SYSTEM_VERSION) return { ok:false as const, code:"design_system_incompatible" as const }; return { ok:true as const, status:c.contract.status==="deprecated"?"deprecated_compatible" as const:"compatible" as const }; }
