"use strict";
const { sql } = require("drizzle-orm");
const { pgTable, uuid, varchar, text, boolean, timestamp, bigint, integer, jsonb, uniqueIndex, index } = require("drizzle-orm/pg-core");
const { organizationDimensionValues } = require("./authz-taxonomy");
const ts = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };
const organizationUnits = pgTable("organization_units", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), hierarchyKey: varchar("hierarchy_key", { length: 100 }).notNull(), unitType: varchar("unit_type", { length: 80 }).notNull(), stableKey: varchar("stable_key", { length: 120 }).notNull(), displayName: varchar("display_name", { length: 180 }).notNull(), description: text("description"), parentUnitId: uuid("parent_unit_id"), dimensionValueId: uuid("dimension_value_id").references(() => organizationDimensionValues.id, { onDelete: "restrict" }), managementLevel: varchar("management_level", { length: 32 }).notNull().default("operational"), status: varchar("status", { length: 32 }).notNull().default("draft"), sortOrder: integer("sort_order").notNull().default(0), metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`), createdByLogtoUserId: varchar("created_by_logto_user_id", { length: 128 }).notNull(), updatedByLogtoUserId: varchar("updated_by_logto_user_id", { length: 128 }).notNull(), ...ts,
}, (t) => ({ uniqueOrgStable: uniqueIndex("organization_units_org_stable_uidx").on(t.logtoOrganizationId, t.stableKey), orgHierarchyStatusIdx: index("organization_units_org_hierarchy_status_idx").on(t.logtoOrganizationId, t.hierarchyKey, t.status), orgTypeStatusIdx: index("organization_units_org_type_status_idx").on(t.logtoOrganizationId, t.unitType, t.status), parentIdx: index("organization_units_parent_idx").on(t.parentUnitId), dimensionValueIdx: index("organization_units_dimension_value_idx").on(t.dimensionValueId), orgSortIdx: index("organization_units_org_sort_idx").on(t.logtoOrganizationId, t.sortOrder) }));
const organizationUnitMemberships = pgTable("organization_unit_memberships", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), unitId: uuid("unit_id").notNull().references(() => organizationUnits.id, { onDelete: "restrict" }), logtoUserId: varchar("logto_user_id", { length: 128 }).notNull(), logtoRoleId: varchar("logto_role_id", { length: 128 }), relationshipType: varchar("relationship_type", { length: 80 }).notNull(), validFrom: timestamp("valid_from", { withTimezone: true }).notNull(), validUntil: timestamp("valid_until", { withTimezone: true }), status: varchar("status", { length: 32 }).notNull().default("scheduled"), assignedByLogtoUserId: varchar("assigned_by_logto_user_id", { length: 128 }).notNull(), reason: text("reason"), ...ts,
}, (t) => ({ unitIdx: index("organization_unit_memberships_unit_idx").on(t.unitId, t.status), orgUserIdx: index("organization_unit_memberships_org_user_idx").on(t.logtoOrganizationId, t.logtoUserId), orgStatusTimeIdx: index("organization_unit_memberships_org_status_time_idx").on(t.logtoOrganizationId, t.status, t.validFrom, t.validUntil) }));
const organizationCapabilityGroupRefs = pgTable("organization_capability_group_refs", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), capability: varchar("capability", { length: 80 }).notNull(), connectorBindingId: uuid("connector_binding_id"), externalType: varchar("external_type", { length: 80 }).notNull(), externalRef: varchar("external_ref", { length: 180 }).notNull(), stableKey: varchar("stable_key", { length: 140 }).notNull(), displayNameCache: varchar("display_name_cache", { length: 180 }), unitId: uuid("unit_id").references(() => organizationUnits.id, { onDelete: "set null" }), dimensionValueId: uuid("dimension_value_id").references(() => organizationDimensionValues.id, { onDelete: "set null" }), syncStatus: varchar("sync_status", { length: 40 }).notNull().default("pending"), lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }), lastErrorJson: jsonb("last_error_json"), metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`), ...ts,
}, (t) => ({ uniqueExternal: uniqueIndex("organization_capability_group_refs_external_uidx").on(t.logtoOrganizationId, t.capability, t.externalType, t.externalRef), orgCapabilityIdx: index("organization_capability_group_refs_org_capability_idx").on(t.logtoOrganizationId, t.capability, t.syncStatus) }));
const organizationAudienceDefinitions = pgTable("organization_audience_definitions", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), stableKey: varchar("stable_key", { length: 120 }).notNull(), displayName: varchar("display_name", { length: 180 }).notNull(), description: text("description"), definitionVersion: integer("definition_version").notNull().default(1), dslVersion: integer("dsl_version").notNull().default(1), definitionJson: jsonb("definition_json").notNull().default(sql`'{}'::jsonb`), status: varchar("status", { length: 32 }).notNull().default("draft"), createdByLogtoUserId: varchar("created_by_logto_user_id", { length: 128 }).notNull(), updatedByLogtoUserId: varchar("updated_by_logto_user_id", { length: 128 }).notNull(), publishedAt: timestamp("published_at", { withTimezone: true }), ...ts,
}, (t) => ({ uniqueOrgStable: uniqueIndex("organization_audience_definitions_org_stable_uidx").on(t.logtoOrganizationId, t.stableKey), orgStatusIdx: index("organization_audience_definitions_org_status_idx").on(t.logtoOrganizationId, t.status) }));
const organizationAudienceExplicitMemberships = pgTable("organization_audience_explicit_memberships", {
  id: uuid("id").primaryKey().defaultRandom(), logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).notNull(), audienceId: uuid("audience_id").notNull().references(() => organizationAudienceDefinitions.id, { onDelete: "restrict" }), memberType: varchar("member_type", { length: 40 }).notNull(), memberRef: varchar("member_ref", { length: 160 }).notNull(), validFrom: timestamp("valid_from", { withTimezone: true }).notNull(), validUntil: timestamp("valid_until", { withTimezone: true }), status: varchar("status", { length: 32 }).notNull().default("active"), reason: text("reason").notNull(), addedByLogtoUserId: varchar("added_by_logto_user_id", { length: 128 }).notNull(), ...ts,
}, (t) => ({ uniqueExplicitMember: uniqueIndex("organization_audience_explicit_memberships_uidx").on(t.audienceId, t.memberType, t.memberRef), orgAudienceIdx: index("organization_audience_explicit_memberships_org_audience_idx").on(t.logtoOrganizationId, t.audienceId, t.status) }));
const organizationStructureVersions = pgTable("organization_structure_versions", { logtoOrganizationId: varchar("logto_organization_id", { length: 128 }).primaryKey(), unitGraphVersion: bigint("unit_graph_version", { mode: "number" }).notNull().default(sql`0`), membershipVersion: bigint("membership_version", { mode: "number" }).notNull().default(sql`0`), audienceVersion: bigint("audience_version", { mode: "number" }).notNull().default(sql`0`), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(), updatedByLogtoUserId: varchar("updated_by_logto_user_id", { length: 128 }), reason: text("reason") });
module.exports = { organizationUnits, organizationUnitMemberships, organizationCapabilityGroupRefs, organizationAudienceDefinitions, organizationAudienceExplicitMemberships, organizationStructureVersions };
