'use strict'
const { canonicalJson, hashContract } = require('./canonical-contract-loader')
const { fingerprintRemoteState } = require('./drift-report')
const SCHEMA_VERSION = '2026-07-logto-authz-plan-v1'
const CIVITAS_API_RESOURCE = 'https://civitas.didaxus.com/api'
const LEGACY_PERMISSION_RE = /^(billing\.|governance\.|account\.|owner\.(read|write|system\.read)$)|[:*]/
function desiredFromManifest(manifest) {
  if (manifest.resource !== CIVITAS_API_RESOURCE) throw new Error(`Logto sync supports only ${CIVITAS_API_RESOURCE}`)
  const activePermissions = manifest.permissions.filter((p)=>p.status === 'active').map((p)=>({ name: p.name, description: p.description || '', resource: p.resource })).sort((a,b)=>a.name.localeCompare(b.name))
  return { resource: manifest.resource, permissions: activePermissions, globalRoles: manifest.globalRoles.slice().sort(), organizationRoles: manifest.organizationRoles.slice().sort(), assignments: Object.fromEntries(Object.entries(manifest.rolePermissionAssignments).sort(([a],[b])=>a.localeCompare(b)).map(([role, permissions])=>[role, permissions.slice().sort()])) }
}
function buildAuthorizationPlan({ contract, remoteState, targetEnvironment = 'unknown' }) {
  const desired = desiredFromManifest(contract.manifest)
  const remoteFingerprint = fingerprintRemoteState(remoteState)
  const plan = { schemaVersion: SCHEMA_VERSION, generatedAt: '1970-01-01T00:00:00.000Z', contractVersion: contract.manifest.contractVersion, catalogHash: contract.manifest.catalogHash, roleModelVersion: contract.manifest.roleModelVersion, contractHash: contract.contractHash || hashContract(contract.manifest), targetEnvironment, targetIdentifier: desired.resource, remoteStateStatus: remoteState.status || (remoteState.source === 'empty-no-credentials' ? 'verification_required' : 'verified'), remoteFingerprint, resource: { desiredIdentifier: desired.resource, remoteId: remoteState.resource?.id || null, operations: [] }, permissions: { create: [], update: [], noop: [], conflicts: [], unmanaged: [] }, globalRoles: { create: [], updateAssignments: [], noop: [], conflicts: [] }, organizationRoles: { create: [], updateAssignments: [], noop: [], conflicts: [] }, drift: { missing: [], extra: [], legacy: [], wrongSurface: [], plannedLeakage: [], wrongResourceIndicator: [] }, legacyScopes: [], customClaims: { operations: [] }, destructiveOperations: [], warnings: [], provenance: { source: 'scripts/logto/authorization-planner.js', catalogHash: contract.manifest.catalogHash, roleModelVersion: contract.manifest.roleModelVersion, contractVersion: contract.manifest.contractVersion } }
  if (!remoteState.resource) { plan.resource.operations.push(operation('create-resource', 'resource', desired.resource, { indicator: desired.resource })); plan.drift.missing.push({ targetType: 'resource', targetId: desired.resource }) }
  else if (remoteState.resource.indicator !== desired.resource) { const item = conflict('wrong-resource-indicator', desired.resource, { actual: remoteState.resource.indicator }); plan.resource.operations.push(item); plan.drift.wrongResourceIndicator.push(item) }
  const remotePermissions = new Map(remoteState.permissions.map((p)=>[p.name,p]))
  for (const permission of desired.permissions) { const remote = remotePermissions.get(permission.name); if (!remote) { const op = operation('create-permission', 'permission', permission.name, permission); plan.permissions.create.push(op); plan.drift.missing.push({ targetType: 'permission', targetId: permission.name }) } else if ((remote.description || '') !== permission.description) plan.permissions.update.push(operation('update-permission', 'permission', permission.name, { id: remote.id, ...permission })); else plan.permissions.noop.push({ name: permission.name, remoteId: remote.id }) }
  const manifestPermissions = new Map(contract.manifest.permissions.map((p)=>[p.name,p]))
  for (const remote of remoteState.permissions) if (!desired.permissions.some((p)=>p.name === remote.name)) { const meta = manifestPermissions.get(remote.name); const driftType = meta && meta.status !== 'active' ? 'planned-leakage' : LEGACY_PERMISSION_RE.test(remote.name) ? 'legacy' : 'extra'; const item = { name: remote.name, remoteId: remote.id, driftType }; plan.permissions.unmanaged.push(item); if (driftType === 'planned-leakage') plan.drift.plannedLeakage.push(item); else if (driftType === 'legacy') { plan.drift.legacy.push(item); plan.legacyScopes.push(item) } else plan.drift.extra.push(item) }
  addRolePlan(plan.globalRoles, desired.globalRoles, desired.assignments, remoteState.globalRoles, 'global-role', plan)
  addRolePlan(plan.organizationRoles, desired.organizationRoles, desired.assignments, remoteState.organizationRoles, 'organization-role', plan)
  return sortPlan(plan)
}
function addRolePlan(bucket, desiredRoles, assignments, remoteRoles, targetType, plan) { const remoteByName = new Map(remoteRoles.map((r)=>[r.name,r])); for (const role of desiredRoles) { const remote = remoteByName.get(role); if (!remote) { const op = operation(`create-${targetType}`, targetType, role, { name: role, permissions: assignments[role] || [] }); bucket.create.push(op); plan?.drift.missing.push({ targetType, targetId: role }) } else { const desiredPerms = assignments[role] || []; const current = remote.permissions || []; const missing = desiredPerms.filter((p)=>!current.includes(p)).sort(); const extra = current.filter((p)=>!desiredPerms.includes(p)).sort(); if (missing.length) { bucket.updateAssignments.push(operation(`assign-${targetType}-permissions`, targetType, role, { id: remote.id, add: missing, preserveExtra: extra })); for (const permission of missing) plan?.drift.missing.push({ targetType: `${targetType}-assignment`, targetId: `${role}:${permission}` }) } else bucket.noop.push({ name: role, remoteId: remote.id, extraAssignmentsPreserved: extra }); for (const permission of extra) { const item = { role, permission, remoteId: remote.id, driftType: permission.startsWith('owner.') && targetType === 'organization-role' ? 'wrong-surface' : LEGACY_PERMISSION_RE.test(permission) ? 'legacy' : 'extra' }; if (item.driftType === 'wrong-surface') plan?.drift.wrongSurface.push(item); else if (item.driftType === 'legacy') plan?.drift.legacy.push(item); else plan?.drift.extra.push(item) } } } for (const remote of remoteRoles) if (!desiredRoles.includes(remote.name)) { const item = { name: remote.name, remoteId: remote.id, driftType: 'unmanaged-role' }; bucket.conflicts.push(item); plan?.drift.extra.push(item) } }
function operation(type, targetType, targetId, payload) { return { operationId: `${type}:${targetId}`, type, targetType, targetId, payload } }
function conflict(type, targetId, details) { return { operationId: `${type}:${targetId}`, type, targetType: 'resource', targetId, details, driftType: type } }
function sortPlan(plan) { const sortById = (items) => items.sort((a,b)=>(a.operationId || a.name).localeCompare(b.operationId || b.name)); for (const section of [plan.resource.operations, plan.permissions.create, plan.permissions.update, plan.permissions.noop, plan.permissions.conflicts, plan.permissions.unmanaged, plan.globalRoles.create, plan.globalRoles.updateAssignments, plan.globalRoles.noop, plan.globalRoles.conflicts, plan.organizationRoles.create, plan.organizationRoles.updateAssignments, plan.organizationRoles.noop, plan.organizationRoles.conflicts]) sortById(section); plan.planHash = require('crypto').createHash('sha256').update(canonicalJson({ ...plan, generatedAt: undefined, planHash: undefined })).digest('hex'); return plan }
module.exports = { SCHEMA_VERSION, buildAuthorizationPlan, desiredFromManifest }
