create table if not exists location_import_runs (
  id uuid primary key default gen_random_uuid(),
  source_name varchar(120) not null,
  source_url text not null,
  source_version varchar(120) not null,
  license varchar(120) not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status varchar(40) not null default 'running',
  countries_count integer not null default 0,
  states_count integer not null default 0,
  cities_count integer not null default 0,
  error_json jsonb
);
create index if not exists location_import_runs_status_idx on location_import_runs(status, started_at);

create table if not exists location_countries (
  id integer generated by default as identity primary key,
  source_id integer not null,
  source_version varchar(120) not null,
  name varchar(160) not null,
  iso2 varchar(2) not null,
  iso3 varchar(3),
  numeric_code varchar(8),
  phone_code varchar(32),
  capital varchar(160),
  currency varchar(16),
  native varchar(160),
  emoji varchar(16),
  region varchar(120),
  subregion varchar(120),
  latitude numeric(10,7),
  longitude numeric(10,7),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists location_countries_source_uidx on location_countries(source_id);
create unique index if not exists location_countries_iso2_uidx on location_countries(iso2);
create index if not exists location_countries_name_idx on location_countries(name);
create index if not exists location_countries_active_name_idx on location_countries(is_active, name);

create table if not exists location_states (
  id integer generated by default as identity primary key,
  source_id integer not null,
  source_version varchar(120) not null,
  country_id integer not null references location_countries(id) on delete cascade,
  country_source_id integer not null,
  name varchar(160) not null,
  state_code varchar(32),
  type varchar(80),
  latitude numeric(10,7),
  longitude numeric(10,7),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists location_states_source_uidx on location_states(source_id);
create index if not exists location_states_country_idx on location_states(country_id, is_active, name);
create index if not exists location_states_name_idx on location_states(name);

create table if not exists location_cities (
  id integer generated by default as identity primary key,
  source_id integer not null,
  source_version varchar(120) not null,
  country_id integer not null references location_countries(id) on delete cascade,
  state_id integer references location_states(id) on delete cascade,
  country_source_id integer not null,
  state_source_id integer,
  name varchar(180) not null,
  latitude numeric(10,7),
  longitude numeric(10,7),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists location_cities_source_uidx on location_cities(source_id);
create index if not exists location_cities_country_idx on location_cities(country_id, is_active, name);
create index if not exists location_cities_state_idx on location_cities(state_id, is_active, name);
create index if not exists location_cities_name_idx on location_cities(name);
