"use strict";
const { normalizeScopeCandidate, projectionIdentity, validateCandidate, assignmentInputFromCandidate, INTEGRATION_REASON_CODES } = require("./scopeCandidateIntegration");
function createScopeProjectionReconciler({ dataScopeRepository, dataScopeAssignmentService, candidateProvider, sourceProvider, roleProvider, taxonomyPort, runtimeConsistencyPort } = {}) {
  async function emit(event) { if (runtimeConsistencyPort?.enqueueOutbox) await runtimeConsistencyPort.enqueueOutbox(event); else if (dataScopeRepository?.recordOutbox) await dataScopeRepository.recordOutbox(event); if (runtimeConsistencyPort?.audit) await runtimeConsistencyPort.audit(event); else if (dataScopeRepository?.audit) await dataScopeRepository.audit({ action: event.eventType, ...event }); }
  return { async reconcileScopeCandidates({ organizationId, subjectId, sourceIds, expectedVersions = {}, reason = "reconcile" } = {}) {
    const raw = await candidateProvider.listCandidates({ organizationId, subjectId, sourceIds });
    const candidates = raw.map(normalizeScopeCandidate);
    const existing = await dataScopeRepository.listAssignments({ organizationId, userId: subjectId });
    const existingDerived = existing.filter((a) => a.sourceType && a.sourceType !== "explicit");
    const byIdentity = new Map(existingDerived.map((a) => [projectionIdentity({ organizationId: a.logtoOrganizationId, subjectId: a.logtoUserId, logtoRoleId: a.logtoRoleId, capability: a.capability, target: { kind: a.scopeKind, dimensionKey: a.dimensionKey, relationshipKey: a.relationshipKey, dimensionValueId: a.dimensionValueId, unitId: a.unitId, resourceRef: a.resourceRef }, source: { type: a.sourceType, id: a.sourceRef, version: a.sourceVersion, status: a.status, validFrom: a.validFrom, validUntil: a.validUntil }, translation: { ruleId: String(a.sourceVersion || "").split(":")[1], ruleVersion: String(a.sourceVersion || "").split(":")[2] || "1" } }), a]));
    const seen = new Set(); const created = []; const updated = []; const invalidated = []; const errors = [];
    for (const candidate of candidates) { const validation = await validateCandidate(candidate, { organizationId, sourceProvider, roleProvider, taxonomyPort }); const identity = projectionIdentity(candidate); seen.add(identity); const current = byIdentity.get(identity); if (!validation.valid) { if (current && current.status === "active") invalidated.push(await dataScopeRepository.updateAssignment(current.id, { status: "invalidated", reason: validation.reasonCode })); else errors.push({ candidateId: candidate.candidateId, reasonCode: validation.reasonCode }); continue; } if (!current) { const result = await dataScopeAssignmentService.createAssignment({ ...assignmentInputFromCandidate(validation.candidate), expectedPolicyVersion: expectedVersions.policyVersion }); created.push(result.assignment); } else if (current.status !== "active") updated.push(await dataScopeRepository.updateAssignment(current.id, { status: "active" })); }
    for (const stale of existingDerived) { const identity = projectionIdentity({ organizationId: stale.logtoOrganizationId, subjectId: stale.logtoUserId, logtoRoleId: stale.logtoRoleId, capability: stale.capability, target: { kind: stale.scopeKind, dimensionKey: stale.dimensionKey, relationshipKey: stale.relationshipKey, dimensionValueId: stale.dimensionValueId, unitId: stale.unitId, resourceRef: stale.resourceRef }, source: { type: stale.sourceType, id: stale.sourceRef, version: stale.sourceVersion, status: stale.status, validFrom: stale.validFrom, validUntil: stale.validUntil }, translation: { ruleId: String(stale.sourceVersion || "").split(":")[1], ruleVersion: String(stale.sourceVersion || "").split(":")[2] || "1" } }); if (!seen.has(identity) && stale.status === "active") invalidated.push(await dataScopeRepository.updateAssignment(stale.id, { status: "revoked", reason: INTEGRATION_REASON_CODES.PROJECTION_REVOKED })); }
    await emit({ eventType: "authorization.scope_projection.reconciled", organizationId, subjectId, created: created.length, updated: updated.length, invalidated: invalidated.length, errors: errors.length, reason });
    return { organizationId, subjectId, created, updated, invalidated, errors, idempotent: true };
  }, async revokeSourceDerivedScopes({ organizationId, sourceType, sourceIds = [], reason = "source_revoked" } = {}) { const assignments = await dataScopeRepository.listAssignments({ organizationId }); const revoked = []; for (const a of assignments.filter((x) => x.sourceType === sourceType && sourceIds.includes(x.sourceRef) && x.status === "active")) revoked.push(await dataScopeRepository.updateAssignment(a.id, { status: "revoked", reason })); await emit({ eventType: "authorization.scope_projection.revoked", organizationId, sourceType, sourceIds, revoked: revoked.length, reason }); return { revoked }; } };
}
module.exports = { createScopeProjectionReconciler };
