"use strict";
const { TRANSLATION_RULES } = require("./scopeCandidateResolver");
const INTEGRATION_REASON_CODES = Object.freeze({ SOURCE_MISSING:"scope_candidate_source_missing", SOURCE_INACTIVE:"scope_candidate_source_inactive", SOURCE_EXPIRED:"scope_candidate_source_expired", ROLE_CONTEXT_MISSING:"scope_candidate_role_context_missing", ROLE_REVOKED:"scope_candidate_role_revoked", TRANSLATION_MISSING:"scope_candidate_translation_missing", TRANSLATION_DEPRECATED:"scope_candidate_translation_deprecated", TARGET_INVALID:"scope_candidate_target_invalid", WRONG_TENANT:"scope_candidate_wrong_tenant", STALE:"scope_candidate_stale", PROJECTION_PENDING:"scope_projection_pending", PROJECTION_ACTIVE:"scope_projection_active", PROJECTION_STALE:"scope_projection_stale", PROJECTION_REVOKED:"scope_projection_revoked", PROJECTION_INVALIDATED:"scope_projection_invalidated", RECONCILIATION_FAILED:"scope_projection_reconciliation_failed", AUDIENCE_STALE:"audience_materialization_stale", AUDIENCE_PENDING:"audience_recompute_pending", AUDIENCE_FAILED:"audience_recompute_failed", CAPABILITY_GROUP_STALE:"capability_group_source_stale", PERSON_RELATIONSHIP_PROVIDER_UNAVAILABLE:"person_relationship_provider_unavailable" });
function isNowActive({ status, validFrom, validUntil }, now = new Date()) { return status === "active" && new Date(validFrom || 0) <= now && (!validUntil || now < new Date(validUntil)); }
function translationRule(ruleId) { return TRANSLATION_RULES[ruleId] || null; }
function normalizeScopeCandidate(candidate = {}) {
  const source = candidate.source || {};
  const ruleId = source.translationRuleId || candidate.translation?.ruleId;
  const ruleVersion = source.translationRuleVersion || candidate.translation?.ruleVersion || "1";
  const target = candidate.target || (candidate.dimensionValueId ? { kind: "dimension", dimensionKey: candidate.dimensionKey, dimensionValueId: candidate.dimensionValueId } : candidate.unitId ? { kind: "unit", relationshipKey: candidate.relationshipKey || "academic.assigned_group", unitId: candidate.unitId } : candidate.resourceRef ? { kind: "resource", relationshipKey: candidate.relationshipKey, resourceRef: candidate.resourceRef } : null);
  if (!target || [target.dimensionValueId, target.unitId, target.resourceRef].filter(Boolean).length !== 1) throw Object.assign(new Error(INTEGRATION_REASON_CODES.TARGET_INVALID), { code: INTEGRATION_REASON_CODES.TARGET_INVALID });
  return { candidateId: candidate.candidateId, organizationId: candidate.organizationId, subjectId: candidate.subjectId, logtoRoleId: candidate.logtoRoleId, capability: candidate.capability, target, source: { type: source.type, id: source.id, version: source.version || candidate.structureVersion || "0", status: source.status || "active", validFrom: source.validFrom || candidate.validFrom, validUntil: source.validUntil || candidate.validUntil }, translation: { ruleId, ruleVersion }, structureVersions: candidate.structureVersions || { membershipVersion: String(candidate.structureVersion || "0"), unitGraphVersion: "0", taxonomyVersion: "0" }, generatedAt: candidate.generatedAt || new Date().toISOString() };
}
function projectionIdentity(candidate) { const c = normalizeScopeCandidate(candidate); const t = c.target; return [c.organizationId, c.subjectId, c.logtoRoleId, c.capability, c.source.type, c.source.id, c.translation.ruleId, c.translation.ruleVersion, t.kind, t.dimensionKey || t.relationshipKey || "", t.dimensionValueId || t.unitId || t.resourceRef].join("::"); }
async function validateCandidate(candidate, { organizationId, sourceProvider, roleProvider, taxonomyPort, now = new Date() } = {}) {
  const c = normalizeScopeCandidate(candidate);
  if (c.organizationId !== organizationId) return { valid: false, reasonCode: INTEGRATION_REASON_CODES.WRONG_TENANT, candidate: c };
  if (!translationRule(c.translation.ruleId)) return { valid: false, reasonCode: INTEGRATION_REASON_CODES.TRANSLATION_MISSING, candidate: c };
  if (!c.logtoRoleId) return { valid: false, reasonCode: INTEGRATION_REASON_CODES.ROLE_CONTEXT_MISSING, candidate: c };
  if (roleProvider?.isRolePathActive && !(await roleProvider.isRolePathActive({ organizationId, subjectId: c.subjectId, logtoRoleId: c.logtoRoleId }))) return { valid: false, reasonCode: INTEGRATION_REASON_CODES.ROLE_REVOKED, candidate: c };
  if (!isNowActive(c.source, now)) return { valid: false, reasonCode: c.source.status === "active" ? INTEGRATION_REASON_CODES.SOURCE_EXPIRED : INTEGRATION_REASON_CODES.SOURCE_INACTIVE, candidate: c };
  if (sourceProvider?.validateSource) { const source = await sourceProvider.validateSource(c); if (!source.valid) return { valid: false, reasonCode: source.reasonCode || INTEGRATION_REASON_CODES.SOURCE_INACTIVE, candidate: c }; }
  if (c.target.kind === "dimension" && taxonomyPort?.resolvePublishedDimensionValue) { const resolved = await taxonomyPort.resolvePublishedDimensionValue({ organizationId, dimensionKey: c.target.dimensionKey, valueId: c.target.dimensionValueId, capability: c.capability }); if (resolved.status !== "active") return { valid: false, reasonCode: INTEGRATION_REASON_CODES.TARGET_INVALID, candidate: c }; }
  return { valid: true, reasonCode: INTEGRATION_REASON_CODES.PROJECTION_ACTIVE, candidate: c };
}
function assignmentInputFromCandidate(c, actorLogtoUserId = "system") { const t = c.target; return { organizationId: c.organizationId, userId: c.subjectId, logtoRoleId: c.logtoRoleId, capability: c.capability, scopeKind: t.kind, dimensionKey: t.dimensionKey, relationshipKey: t.relationshipKey, dimensionValueId: t.dimensionValueId, unitId: t.unitId, resourceRef: t.resourceRef, sourceType: c.source.type, sourceRef: c.source.id, sourceVersion: `${c.source.version}:${c.translation.ruleId}:${c.translation.ruleVersion}`, actorLogtoUserId, validFrom: c.source.validFrom, validUntil: c.source.validUntil, reason: `derived:${c.translation.ruleId}/${c.translation.ruleVersion}` }; }
module.exports = { INTEGRATION_REASON_CODES, normalizeScopeCandidate, projectionIdentity, validateCandidate, assignmentInputFromCandidate, isNowActive };
