"use strict";
const {deny,organization,dimensions,relationships,self,or,assertConstraintSafe}=require("./dataScopeConstraint");
const {DATA_SCOPE_REASON_CODES}=require("./dataScopeReasonCodes");
function composeDimensionConstraint(strategy,assignments){const clauses=[]; for(const key of strategy.requiredDimensionKeys||[]){const ids=[...new Set(assignments.filter(a=>["dimension","unit"].includes(a.scopeKind)&&((a.dimensionKey===key)||(key.startsWith("organization.")&&a.unitId))).map(a=>a.dimensionValueId||a.unitId))]; if(!ids.length) return deny(DATA_SCOPE_REASON_CODES.ASSIGNMENT_MISSING); clauses.push({dimensionKey:key,operator:"in",valueIds:ids});} return dimensions(clauses);}
function relationshipRefFor(key,c){ if(key.startsWith("academic.")){ if(key==="academic.related_student") return c.resourceRef; return c.resourceRef||c.unitId; } return c.resourceRef||c.unitId; }
function composeRelationshipConstraint(strategy,candidates){const clauses=[]; for(const key of strategy.relationshipKeys||[]){const refs=[...new Set(candidates.filter(c=>(!strategy.relationshipType || c.source?.relationshipType===strategy.relationshipType) && (!c.expiresAt||new Date(c.expiresAt)>new Date())).map(c=>relationshipRefFor(key,c)).filter(Boolean))]; if(refs.length) clauses.push({relationshipKey:key,targetType:key.includes("student")||key.endsWith("self")?"person":(key.includes("group")||key.includes("unit")?"unit":"resource"),targetRefs:refs});} return clauses.length?relationships(clauses):deny(DATA_SCOPE_REASON_CODES.ASSIGNMENT_MISSING);}
function composeGroupLeadershipConstraint(strategy,candidates){ const refs=[...new Set(candidates.filter(c=>c.source?.relationshipType===(strategy.relationshipType||"leads")).map(c=>c.resourceRef||c.unitId).filter(Boolean))]; return refs.length?relationships([{relationshipKey:"academic.assigned_group",targetType:"unit",targetRefs:refs}]):deny(DATA_SCOPE_REASON_CODES.ASSIGNMENT_MISSING);}
function composeRolePathConstraint({strategy,organizationId,subjectId,assignments=[],candidates=[]}){ const kind=strategy.name||strategy.strategy; let c; if(kind==="organization"||strategy.strategy==="organization") c=organization(organizationId); else if(kind==="global_owner") c={kind:"global_owner"}; else if(kind==="self") c=self(subjectId); else if(kind==="self_or_organization") c=or([self(subjectId),organization(organizationId)]); else if(kind==="organization_and_units"||strategy.strategy==="dimensions") c=composeDimensionConstraint(strategy,assignments); else if(["academic_relationship","teaching_assignments","planning_relationship","planning_editable","planning_owned","assigned_reviews","assigned_approvals","approved_plans","community_membership","community_moderation","hr_relationship","payroll_relationship","scheduling_relationship","support_relationship","communication_relationship"].includes(kind)||strategy.strategy==="relationships") c=composeRelationshipConstraint(strategy,candidates); else if(strategy.strategy==="group_leadership") c=composeGroupLeadershipConstraint(strategy,candidates); else c=deny(DATA_SCOPE_REASON_CODES.STRATEGY_UNKNOWN); return assertConstraintSafe(c);}
function composeAcrossRolePaths(paths){const allowed=paths.filter(p=>p.allowed&&p.constraint&&p.constraint.kind!=="deny"); if(!allowed.length) return deny(DATA_SCOPE_REASON_CODES.MULTIPLE_ROLE_PATHS_INCOMPLETE); return allowed.length===1?allowed[0].constraint:or(allowed.map(p=>p.constraint));}
module.exports={composeRolePathConstraint,composeAcrossRolePaths};
